# WARN: This configuration file is only applied during initial setup using the USB installer, and not during OTA updates via Web.Auto.
network:
  version: 2
  renderer: networkd
  ethernets:
    # 1GbE SW Hub
    # Internet, HMI
    enp5s0f0:
      dhcp4: false
      dhcp6: false
      optional: false
    # 10GbE SW Hub
    enp5s0f1:
      addresses: [192.168.30.11/24]
      dhcp4: false
      dhcp6: false
      optional: false
      mtu: 9000
    # Internal 10GbE SW IC
    # RADAR
    enp3s0:
      dhcp4: false
      dhcp6: false
      optional: false
    # Internal 10GbE SW IC
    # LiDAR, Sub ECU
    enp4s0:
      addresses: [192.168.1.11/24, 10.13.1.166/24]
      dhcp4: false
      dhcp6: false
      mtu: 9000
      optional: false
  vlans:
    # LiDAR / radar PTP
    vlan.11:
      id: 11
      link: enp3s0
    vlan.12:
      id: 12
      link: enp3s0
    vlan.13:
      id: 13
      link: enp3s0
    vlan.14:
      id: 14
      link: enp3s0
    vlan.15:
      id: 15
      link: enp3s0
    vlan.16:
      id: 16
      link: enp3s0
    # Internet
    vlan.100:
      id: 100
      link: enp5s0f0
      dhcp4: false
      dhcp6: false
      addresses: [192.168.251.11/24]
      optional: true
      nameservers:
        addresses: [8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.251.1
          scope: link
          table: 100
        - to: 0.0.0.0/0
          via: 192.168.251.1
          metric: 90
      routing-policy:
        - from: 192.168.251.11
          table: 100
          priority: 100
    vlan.200:
      id: 200
      link: enp5s0f0
      dhcp4: false
      dhcp6: false
      addresses: [192.168.252.11/24]
      optional: true
      nameservers:
        addresses: [8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.252.1
          scope: link
          table: 200
        - to: 0.0.0.0/0
          via: 192.168.252.1
          metric: 100
      routing-policy:
        - from: 192.168.252.11
          table: 200
          priority: 200
    vlan.300:
      id: 300
      link: enp5s0f0
      dhcp4: false
      dhcp6: false
      addresses: [192.168.253.11/24]
      optional: true
      nameservers:
        addresses: [8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.253.1
          scope: link
          table: 300
        - to: 0.0.0.0/0
          via: 192.168.253.1
          metric: 110
      routing-policy:
        - from: 192.168.253.11
          table: 300
          priority: 300
    vlan.400:
      id: 400
      link: enp5s0f0
      dhcp4: false
      dhcp6: false
      addresses: [192.168.254.11/24]
      optional: true
      nameservers:
        addresses: [8.8.8.8]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.254.1
          scope: link
          table: 400
        - to: 0.0.0.0/0
          via: 192.168.254.1
          metric: 120
      routing-policy:
        - from: 192.168.254.11
          table: 400
          priority: 400
    vlan.500:
      id: 500
      link: enp5s0f0
      dhcp4: false
      dhcp6: false
      addresses: [192.168.20.11/24]
