network:
  version: 2
  ethernets:
    # HMI
    eth0:
      addresses: [192.168.30.51/24]
      dhcp4: false
      dhcp6: false
      optional: true
    # internet: For Debug
    eth1:
      dhcp4: true
      dhcp6: false
      optional: true
