network:
  version: 2
  renderer: networkd
  ethernets:
    # HMI
    enp1s0:
      addresses: [192.168.20.51/24]
      dhcp4: false
      dhcp6: false
      optional: false
    # For debugging purpose
    enp2s0:
      dhcp4: true
      dhcp6: false
      optional: true
