network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      dhcp4: false
      dhcp6: false
      addresses: [192.168.20.31/24]
    eth0: # debug purpose
      dhcp4: true
      dhcp-identifier: mac
      optional: true
