network:
  version: 2
  renderer: networkd
  ethernets:
    # 1GbE SW Hub
    # HMI, PTPv2
    enp5s0f0:
      addresses: [192.168.20.21/24]
      dhcp4: false
      dhcp6: false
      optional: true
    # 10GbE SW Hub
    enp5s0f1:
      addresses: [192.168.30.21/24]
      dhcp4: false
      dhcp6: false
      mtu: 9000
      optional: true
    # Internal 10GbE SW IC
    # LiDAR, Main ECU
    enp4s0:
      addresses: [192.168.1.21/24]
      dhcp4: false
      dhcp6: false
      mtu: 9000
      optional: true
