network:
  version: 2
  ethernets:
    # HMI
    eno1:
      addresses: [192.168.30.31/24]
      dhcp4: false
      dhcp6: false
    # internet: For Debug
    enp2s0:
      dhcp4: true
      dhcp6: false
      optional: true
