network:
  version: 2
  renderer: networkd
  ethernets:
    # 1GbE SW Hub
    # HMI
    enp5s0f0:
      addresses: [192.168.20.21/24]
      dhcp4: false
      dhcp6: false
      optional: false
    # 10GbE SW Hub
    enp5s0f1:
      addresses: [192.168.30.21/24]
      dhcp4: false
      dhcp6: false
      mtu: 9000
      optional: false
    # For PTP of LiDAR and RADAR
    enp3s0:
      dhcp4: false
      dhcp6: false
      mtu: 9000
      optional: false
    # Internal 10GbE SW IC
    # LiDAR, Sub ECU
    enp4s0:
      addresses: [192.168.1.21/24, 10.13.1.176/24]
      dhcp4: false
      dhcp6: false
      macaddress: 02:00:00:00:01:10 # To avoid having the same address as Main ECU
      optional: false
  vlans:
    vlan.11:
      id: 11
      link: enp3s0
    vlan.12:
      id: 12
      link: enp3s0
    vlan.13:
      id: 13
      link: enp3s0
    vlan.14:
      id: 14
      link: enp3s0
    vlan.15:
      id: 15
      link: enp3s0
    vlan.16:
      id: 16
      link: enp3s0
