# cspell: ignore autowaret AWSCRT epoll libaws libnetty orcexec rwxm rwmx unarchived

# Policy block declaration syntax:
#
#   :baseline=(<policy-mode>[,<policy-matching-mode>])
#
# "<policy-mode>" option can be one of the two policy modes:
#   "enforce": Enforce mode (default)
#       Blocks violated actions and generates security event messages
#   "complain": Complain mode
#       Generates security event messages but allows violated actions
#
# "<policy-matching-mode>" option can be one of the following:
#   "strict": Strict mode (default mode when not specified)
#       Full policy matching by path and hash
#   "loose": Loose mode
#       Check execution action only and match policy by hash
#
:baseline=(enforce)

# Rule declaration syntax: Add or overwrite rule from collected baseline
#
#   <path> [<perm>] [<hash>]
#
# "<path>": File path of a policy rule. A file path must begin with a forward
#           slash "/" character.
#   wildcard support
#       "*": Single directory or name matching wildcard
#       "**": Recursive directory wildcard
#
# "<perm>": Rule permissions
#   "r": read permission
#   "w": write permission
#   "m": load permission (for example, load libc.so.6)
#   "x": executable permission
#   "..": default (rmx for baseline) or exists permission
#   empty / "-": empty, no permission specified
#
# "<hash>": rule hash
#   SHA1 in HEX string: Hash value
#   "[<sha1-hash1>,<sha1-hash2>,..]": Array of multiple hashes
#   "..": default, no hash specified, ignore hash check
#   empty / "-": empty, same as ".."
#
# Example for JIT support:
#   The ORC JIR library generates the JIT code and executes the code in the
#   path "/tmp/orcexec.EBI4eb" (the EBI4eb is random string). The following
#   shows the rule example:
#       /tmp/orcexec.* rwmx
#
/root/.cache/JNA/temp/jna*.tmp rwxm
/tmp/AWSCRT_*libaws-crt-jni.so rwxm
/run/user/1000/orcexec.* rwxm
/home/autoware/orcexec.* rwxm
/tmp/orcexec.* rwxm
/opt/autoware/utils/bin/* rx
/greengrass/v2/logs/** rw
/root/.greengrass_setup/gg_setup/* rw
/greengrass/v2/packages/artifacts-unarchived/com.customized.AmazonCloudwatchPublisher/*/com.customized.AmazonCloudwatchPublisher/setup_venv.bash rx
/tmp/libnetty_transport_native_epoll_x86_64*.so rm
/greengrass/v2/packages/artifacts-unarchived/fms-prd-edge-autowaret4b-edge-mob-proxy/*/fms-prd-edge-autowaret4b-edge-mob-proxy/app rx
/home/autoware/**/*.yml r
/home/autoware/**/*.yaml r
/home/autoware/**/*.xml r
/home/autoware/**/*.py rx
/opt/autoware/**/*.osm r
/opt/autoware/**/*.yaml r
/opt/autoware/**/*.pcd r
