:baseline=(enforce)

# check listed interpreters with allowable file name for execution
interpreter_execute_config [
    bash *
    sh *
    python* *
    perl *.pl
    node *.js
]
#    python* *.py

# interpreters open checking rule by file name
interpreter_open_check_list [
#    bash *.sh;profile;.bashrc
#    sh *.sh;profile;.bashrc
#    python* *.py
#    perl *.pl
#    node *.js
]

# custom rules

# /path/to/my_script
/opt/ros/galactic/bin/xacro
/tmp/launch_params_*
