# cspell: ignore BMHOOK uprobe xcar

## Pattern block and rule syntax:
#   :<policy_block_name>[=(<option_fields>)[[<feature_fields>]]]
#   [<enforcement>|<enabling>] <event_expression>
#   [<enforcement>|<enabling>] <event_expression>
#
## <policy_block_name>:
#   "pattern.eop": BM_ID_EOP_... elevation of privilege event type
#   "pattern.sp": BM_ID_SP_... suspicious event type
#   "pattern.sp.xcar": BM_ID_SP_XCAR_... suspicious event type and xcar sub-event type
#
## <option_fields>:
#   [<enforcement>][,<selection>]..
#
#   - The fields order does not matter, since every defined option values are unique.
#   <enforcement>
#       "enforce": kill process who violate the EoP rule. (default), (action + detection)
#       "complain": send event w/o kill the process who violate the EoP rule, (detection)
#   <selection>
#       "all": load all related event (default)
#       "select": load only selective events defined under the block
#   <enabling>
#       "enable": (default)
#       "disable":
#
## <feature_fields>
#       [<feature>][|<feature>]..
#   <feature>
#       test, bm, am, ac, im, edr, xdr, file, self_protection
#       default: [bm|xdr]
#       empty [] feature set will disable the pattern block, as same as option disable
#
## <event_expression>
#
#   "BMHOOK_EVENT_ID_<name>": by event ID name
#   "ID=<value>": by event ID value
#       in decimal: ID=33554433
#       in oct: ID=0200000001
#       in hex: ID=0x2000001
#
#   - Specifying with ID name require engine recognize the event name in advance. If pattern
#     is newer than the engine, then the newly added ID name is unable to be used in config
#     file. Therefore, the new event should be configure via ID value instead of ID name.
#   - See available event ID by command "atom bm E [<pattern-file>] -P | jq ".desc[]"", the
#     "<pattern-file>" is optional, it use installed one without the input file.
#

## uncomment following line to disable uprobe functionality
# :pattern.bm=(disable)

:pattern.bm=(enforce)
:pattern.bm.xcar=(enforce)
:pattern.eop=(enforce)
:pattern.sp=(enforce)
:pattern.sp.xcar=(enforce)

:pattern.bm=(select,disable)
BMHOOK_EVENT_ID_BM_ACCEPT_POST
:pattern.sp=(select,disable)
ID=50331663
