# Default <mode> option:
#   "bypass": In bypass mode, network traffic is ignored. Note that the child
#       configure block cannot override this mode due to the optimization
#       shortcuts.
#   "enforce": In enforce mode, network traffic is sent to the DPI module for
#       analysis.
#   "monitor": In monitor mode, network traffic is sent to the DPI module for
#       analysis. However, the system does not block network traffic
#       regardless of the analysis result.
#
:default=enforce

# Rule declaration syntax (parameters in "[]" are optional).
#   <mode> <ip_address>[/<netmask_bit_number>] [<port>,<port_range>,..]
#
# Examples:
#   monitor 8.8.8.8
#   bypass 2404:6800:4008:802::2004 1-1000,3000
#   bypass 1.1.1.1/24
#   monitor www.google.com 443
#
bypass 192.168.30.21/24


# Configuration block for PROT tls protocol policy
#
:prot.tls=monitor
# bypass 192.168.1.1/24

# Subclass policy for cipher suites check
#
# :prot.tls.cipher=enforce

# Subclass policy for certificate validation
#
# :prot.tls.cert=enforce
