- repository: autowarefoundation/autoware
  files:
    # General
    - source: .github/dependabot.yaml
    - source: .github/workflows/backport.yaml
    - source: .github/workflows/cancel-previous-workflows.yaml
    - source: .github/workflows/github-release.yaml
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .clang-format
    - source: .clang-tidy
    - source: .fdignore
    - source: .gitignore
    - source: .markdownlint.yaml
    - source: .pre-commit-config.yaml
    - source: .pre-commit-config-ansible.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .rgignore
    - source: .shellcheckrc
    - source: .yamllint.yaml
    - source: CPPLINT.cfg
    - source: setup.cfg

    # Autoware Workflows
    - source: .github/workflows/load-env.yaml

    - source: .github/workflows/setup-universe.yaml
      dest: .github/workflows/setup-local-dev-env.yaml
      pre-commands: |
        sd "setup-universe" "setup-local-dev-env" {source}
        sd "universe" "local_dev_env" {source}
        sd -s -- \
        "     - name: Set git config" \
        "     - name: Generate token
                id: generate-token
                uses: tibdex/github-app-token@v1
                with:
                  app_id: \${{ secrets.APP_ID }}
                  private_key: \${{ secrets.PRIVATE_KEY }}

              - name: Set git config" {source}
        sd "secrets.GITHUB_TOKEN" "steps.generate-token.outputs.token" {source}
        sd "runs-on: ubuntu-latest" "runs-on: ubuntu-latest-m" {source}

    - source: .github/workflows/pre-commit-ansible.yaml
      pre-commands: |
        sd -s -- \
        "     - name: Set git config" \
        "     - name: Generate token
                id: generate-token
                uses: tibdex/github-app-token@v1
                with:
                  app_id: \${{ secrets.APP_ID }}
                  private_key: \${{ secrets.PRIVATE_KEY }}

              - name: Set git config" {source}
        sd "secrets.GITHUB_TOKEN" "steps.generate-token.outputs.token" {source}

    # Setup
    - source: amd64.env
    - source: arm64.env

    - source: setup-dev-env.sh
      pre-commands: |
        sd "autoware.dev_env" "pilot_auto.dev_env" {source}
        sd "dev_env.universe" "dev_env.local_dev_env" {source}

    - source: ansible-galaxy-requirements.yaml
      pre-commands: |
        sd "\z" \
        "
          ##### generated by sync-files #####
        " {source}
        latest_hash=$(git ls-remote --heads https://github.com/autowarefoundation/autoware.git refs/heads/main | awk '{print $1}')
        sd "\z" \
        "
          - name: https://github.com/autowarefoundation/autoware.git#/ansible
            type: git
            version: $latest_hash
        " {source}
        sd "\z" \
        "
          # When you use your own customized ./src/ecu_system_setup,
          # comment out git settings, uncomment source settings and in autoware.repos
          # - source: ./src/ecu_system_setup
          #   type: dir
          - name: git@github.com:tier4/autoware_ecu_system_setup.git
            type: git
            version: main
        " {source}

    # Docker
    - source: docker/README.md
      pre-commands: |
        perl -pi -e 's/(?<!:\/\/)(?<!\[)(autowarefoundation)/tier4/g' {source}
        perl -pi -e 's/(?<!:\/\/)(?<!\[)(autoware-universe)/pilot-auto/g' {source}
        perl -pi -e 's/(?<!:\/\/)(?<!\[)(Autoware Universe)/Pilot.Auto/g' {source}
        perl -pi -e 's/(?<!:\/\/)(?<!\[)(Autoware)/Pilot.Auto/g' {source}
        sd -s "../" "https://github.com/autowarefoundation/autoware/tree/main/" {source}

    - source: docker/build.sh
      pre-commands: |
        sd "autowarefoundation" "tier4" {source}
        sd "autoware" "pilot-auto" {source}

    - source: docker/docker-bake.hcl
      dest: docker/pilot-auto/docker-bake.hcl
      pre-commands: |
        sd "autoware-universe" "pilot-auto" {source}

    - source: docker/Dockerfile
      dest: docker/pilot-auto/Dockerfile
      pre-commands: |
        sd "universe" "local_dev_env" {source}
