release_supervisors: # people in charge of all releases
  - rej55

base_branch_for_release: main
autoware_repos_file: autoware.repos
additional_repos_files:
  - simulator.repos
  - tools.repos

releases:
  - version: v0.36
    release_managers:
      - rej55
    released_repositories:
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.36
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.36
  - version: v0.41
    release_managers:
      - rej55
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.41
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.41
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.41
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.41
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.41
  - version: v0.42
    release_managers:
      - rej55
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.42
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.42
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.42
  - version: v0.43
    release_managers:
      - hayato-m126
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.43
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.43
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.43
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.43
  - version: v0.44
    release_managers:
      - TaikiYamada4
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.44
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.44
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.44
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.44
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.44
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.44
  - version: v0.45
    release_managers:
      - TaikiYamada4
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.45
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.45
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.45
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.45
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.45
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.45
  - version: v0.46
    release_managers:
      - TaikiYamada4
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.46
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.46
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.46
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.46
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.46
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.46
  - version: v0.47
    release_managers:
      - TaikiYamada4
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.47
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.47
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.47
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.47
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.47
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.47
  - version: v0.48
    release_managers:
      - TaikiYamada4
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.48
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.48
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.48
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.48
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.48
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.48
      - repo_name_in_autoware_repos: autoware/ad_api_adaptor
        release_version: v0.48
    released_ansible_repos: # from ansible-galaxy-requirements.yaml file
      - repo_full_name: tier4/autoware_ecu_system_setup # github repo full name (owner/repo) derived from name field in collections
        release_version: v0.48
      - repo_full_name: tier4/edge-auto-jetson
        release_version: v0.48
  - version: v0.49
    release_managers:
      - masaharuTakano
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.49
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.49
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.49
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.49
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.49
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.49
  - version: v0.50
    release_managers:
      - masaharuTakano
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.50
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.50
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.50
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.50
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.50
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.50
  - version: v0.51
    release_managers:
      - masaharuTakano
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.51
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.51
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.51
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.51
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.51
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.51
  - version: v0.52
    release_managers:
      - masaharuTakano
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.52
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.52
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.52
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.52
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.52
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.52
  - version: v0.53
    release_managers:
      - masaharuTakano
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.53
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.53
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.53
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.53
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.53
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.53
  - version: v0.54
    release_managers:
      - masaharuTakano
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.54
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.54
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.54
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.54
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.54
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.54
  - version: v0.55
    release_managers:
      - masaharuTakano
    released_repositories:
      - repo_name_in_autoware_repos: autoware/core
        release_version: v0.55
      - repo_name_in_autoware_repos: autoware/launcher
        release_version: v0.55
      - repo_name_in_autoware_repos: autoware/universe
        release_version: v0.55
      - repo_name_in_autoware_repos: autoware/aip_launcher
        release_version: v0.55
      - repo_name_in_autoware_repos: autoware/tier4_autoware_msgs
        release_version: v0.55
      - repo_name_in_autoware_repos: v2x/vehicle2infrastructure
        release_version: v0.55
