# This is required for Continuous Integration for Autoware using the simulator
# and remote update (Over The Air update) to real cars.
# If you have any additional questions, please contact us at #tier4-dev channel.

# cSpell: ignore persistents buildspecs

version: 2

artifacts:
  - name: signage
    build:
      type: custom
      runtime:
        type: standard1/amd64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
          import_path: src
      linux_parameters:
        kernel_version: 5.15.0-72-generic
      phases:
        - name: environment-setup
          user: root
          exec: ./.webauto-ci/signage/environment-setup/run.sh
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/signage/environment-setup/**/*
        - name: ecu-system-setup
          user: autoware
          exec: ./.webauto-ci/signage/ecu-system-setup/run.sh
          environment_variables:
            ECU_SYSTEM_SETUP_ANSIBLE_PLAYBOOK: ansible/playbooks/x2_signage.yaml
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/signage/ecu-system-setup/**/*
              - src/ecu_system_setup/**/*
              - ansible/**/*
              - ansible-galaxy-requirements.yaml
      base_container_image:
        from: ubuntu:22.04
      output_rootfs_image:
        from: ecu-system-setup
        persistent_file_path: /etc/ota/persistents.txt
      output_installer_image:
        from: ecu-system-setup
        type: iso
        base_iso: ubuntu-20.04.3-live-server-amd64

  - name: voice-system
    build:
      type: custom
      runtime:
        type: standard1/amd64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
          import_path: src
      linux_parameters:
        kernel_version: 5.15.0-72-generic
      phases:
        - name: environment-setup
          user: root
          exec: ./.webauto-ci/signage/environment-setup/run.sh
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/signage/environment-setup/**/*
        - name: ecu-system-setup
          user: autoware
          exec: ./.webauto-ci/signage/ecu-system-setup/run.sh
          environment_variables:
            ECU_SYSTEM_SETUP_ANSIBLE_PLAYBOOK: ansible/playbooks/x2_voice_system.yaml
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/signage/ecu-system-setup/**/*
              - src/ecu_system_setup/**/*
              - ansible/**/*
              - ansible-galaxy-requirements.yaml
      base_container_image:
        from: ubuntu:22.04
      output_rootfs_image:
        from: ecu-system-setup
        persistent_file_path: /etc/ota/persistents.txt
      output_installer_image:
        from: ecu-system-setup
        type: iso
        base_iso: ubuntu-20.04.3-live-server-amd64

release:
  name_template: ${datetime}-${version}
  components:
    - name: signage
      deployment:
        type: rootfs
        artifact: signage
      alternative_deployments:
        - type: installer
          artifact: signage
    - name: voice-system
      deployment:
        type: rootfs
        artifact: voice-system
      alternative_deployments:
        - type: installer
          artifact: voice-system

scenario_parameter_groups:
  # Necessary to update the parameters for each vehicle type
  - name: common
    parameters:
      __ego_center_x__: 2.08875 # ego_dimensions_length / 2.0 - rear_overhang
      __ego_center_y__: 0
      __ego_center_z__: 1.54 # ego_dimensions_height / 2.0
      __ego_dimensions_width__: 2.3 # wheel_tread + left_overhang + right_overhang
      __ego_dimensions_length__: 7.1734 # wheel_base + front_overhang + rear_overhang
      __ego_dimensions_height__: 3.06
      wheel_radius: 0.3725
      wheel_width: 0.215
      wheel_base: 4.76 # between front wheel center and rear wheel center
      wheel_tread: 1.754 # front:1.754 rear:1.564 between left wheel center and right wheel center
      front_overhang: 0.9154 # between front wheel center and vehicle front
      rear_overhang: 1.498 # between rear wheel center and vehicle rear
      left_overhang: 0.273 # 1.150-2.08/2 between left wheel center and vehicle left
      right_overhang: 0.273 # between right wheel center and vehicle right
      max_steer_angle: 0.646 # [rad]
      stop_line_distance: 0.5 # param name in autoware_launch: stop_margin
      blind_spot_stop_line_distance: 1.0 # param name in autoware_launch: stop_line_margin
      obstacle_stop_line_distance: 6.0 # param name in autoware_launch: max_longitudinal_margin
      crosswalk_stop_line_distance: 3.5 # param name in autoware_launch: stop_distance_from_crosswalk
      walkway_stop_line_distance: 1.5 # param name in autoware_launch: stop_distance_from_crosswalk
      intersection_stop_line_distance: 3.0 # param name in autoware_launch: stop_line_margin
      traffic_light_stop_line_distance: 0.5 # param name in autoware_launch: stop_margin
      run_out_stop_line_distance: 2.5 # param name in autoware_launch: stop_margin
