# This is required for Continuous Integration for Autoware using the simulator
# and remote update (Over The Air update) to real cars.
# If you have any additional questions, please contact us at #tier4-dev channel.

version: 2

artifacts:
  - name: main
    metadata:
      play-ondemand.ci.web.auto/buildspec: Autoware-Humble
    build:
      type: custom
      runtime:
        type: standard1/amd64/large
      source:
        vcstool:
          repositories_files:
            - autoware.repos
            - simulator.repos
          import_path: src
      environment_variables:
        AUTOWARE_PATH: /home/autoware/pilot-auto
        ML_MODELS_PATH: /opt/autoware/mlmodels
        DEBIAN_FRONTEND: noninteractive
        LANG: C.UTF-8
      linux_parameters:
        kernel_version: 5.15.0-72-generic
      phases:
        - name: environment-setup
          user: root
          exec: ./.webauto-ci/main/environment-setup/run.sh
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/main/environment-setup/**/*
        - name: autoware-setup
          user: autoware
          exec: ./.webauto-ci/main/autoware-setup/run.sh
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/main/autoware-setup/**/*
              - ansible/**/*
              - ansible-galaxy-requirements.yaml
              - amd64.env
          incremental_build:
            enabled: true
        - name: autoware-build
          user: autoware
          exec: ./.webauto-ci/main/autoware-build/run.sh
          environment_variables:
            PARALLEL_WORKERS: "32"
            CCACHE_DIR: /tmp/build/cache/ccache
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
            - name: ccache
              mountpoint: /tmp/build/cache/ccache
          build_result_reuse:
            key_files:
              - .webauto-ci/main/autoware-build/**/*
              - src/**/*
              - "!src/ecu_system_setup/**"
          incremental_build:
            enabled: true
        - name: ecu-system-setup
          user: autoware
          exec: ./.webauto-ci/main/ecu-system-setup/run.sh
          environment_variables:
            ECU_SYSTEM_SETUP_SOURCE_PATH: src/ecu_system_setup
            ECU_SYSTEM_SETUP_ANSIBLE_PLAYBOOK: src/ecu_system_setup/common.yaml
          caches:
            - name: apt-lists
              mountpoint: /var/lib/apt/lists
            - name: apt-archives
              mountpoint: /var/cache/apt/archives
          build_result_reuse:
            key_files:
              - .webauto-ci/main/ecu-system-setup/**/*
              - src/ecu_system_setup/**/*
      base_container_image:
        from: ubuntu:22.04
        # from: ghcr.io/tier4/pilot-auto/base-image:latest # use base image
      output_container_image:
        from: autoware-build
        workdir: /home/autoware/pilot-auto
        user: autoware
      output_rootfs_image:
        from: ecu-system-setup
        persistent_file_path: /home/autoware/pilot-auto/.webauto-ci/main/ecu-system-setup/persistents.txt
      output_installer_image:
        from: ecu-system-setup
        type: iso
        base_iso: ubuntu-20.04.3-live-server-amd64

simulations:
  - name: planning_sim_v2
    type: planning_sim_v2
    scenario_parameter_group: common # Necessary to define the name for each vehicle type
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium
      parameters:
        vehicle_model: lexus
        sensor_model: aip_xx1
        autoware_launch_package: autoware_launch
        autoware_launch_file: planning_simulator.launch.xml
        architecture_type: awf/universe/20230906
        initialize_duration: "90"

  - name: obstacle_detection
    type: obstacle_detection
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

  - name: ndt_convergence
    type: ndt_convergence
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/large

  - name: localization
    type: localization
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/large

  - name: obstacle_segmentation
    type: obstacle_segmentation
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

  - name: performance_diag
    type: performance_diag
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

  - name: perception
    type: perception
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: gpu1/amd64/large
      pre_tasks:
        - exec: source /home/autoware/pilot-auto/install/setup.bash && ros2 launch lidar_centerpoint lidar_centerpoint.launch.xml model_name:=centerpoint_tiny model_path:=/home/autoware/autoware_data/lidar_centerpoint model_param_path:=$(ros2 pkg prefix lidar_centerpoint --share)/config/centerpoint_tiny.param.yaml build_only:=true
          mounts:
            - volume: model
      volumes:
        - name: model
          path: /home/autoware/autoware_data/lidar_centerpoint
          preserve_original_files: true

  - name: yabloc
    type: yabloc
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

  - name: eagleye
    type: eagleye
    simulator:
      deployment:
        type: container
        artifact: main
      runtime:
        type: standard1/amd64/medium

release:
  components:
    - name: autoware
      deployment:
        type: rootfs
        artifact: main

scenario_parameter_groups:
  # Necessary to update the parameters for each vehicle type
  - name: common
    parameters:
      __ego_center_x__: 1.345
      __ego_center_y__: 0
      __ego_center_z__: 1.25
      __ego_dimensions_width__: 1.896
      __ego_dimensions_length__: 4.89
      __ego_dimensions_height__: 2.5
      wheel_radius: 0.383
      wheel_width: 0.235
      wheel_base: 2.79 # between front wheel center and rear wheel center
      wheel_tread: 1.64 # between left wheel center and right wheel center
      front_overhang: 1.0 # between front wheel center and vehicle front
      rear_overhang: 1.1 # between rear wheel center and vehicle rear
      left_overhang: 0.128 # between left wheel center and vehicle left
      right_overhang: 0.128 # between right wheel center and vehicle right
      max_steer_angle: 0.70 # [rad]
      stop_line_distance: 0.0 # param name in autoware_launch: stop_margin
      blind_spot_stop_line_distance: 1.0 # param name in autoware_launch: stop_line_margin
      obstacle_stop_line_distance: 5.0 # param name in autoware_launch: max_longitudinal_margin
      crosswalk_stop_line_distance: 3.5 # param name in autoware_launch: stop_distance_from_crosswalk
      walkway_stop_line_distance: 3.5 # param name in autoware_launch: stop_distance_from_crosswalk
      intersection_stop_line_distance: 3.0 # param name in autoware_launch: stop_line_margin
      traffic_light_stop_line_distance: 0.0 # param name in autoware_launch: stop_margin
      run_out_stop_line_distance: 2.5 # param name in autoware_launch: stop_margin
