# cSpell:ignore rexmit

# cyclonedds
cyclonedds:
  network_interface:
    - { address: enp5s0f1, priority: 1 } # Prioritize 10Gb interface
    - { address: vlan.500, priority: 0 }
  minimum_socket_receive_buffer_size: 100MB
  minimum_socket_send_buffer_size: 10MB
  max_message_size: 8950B
  fragment_size: 8850B
  max_rexmit_message_size: 8950B
  water_mark_whc_high: 4MB
  water_mark_whc_low: 10kB
ipv4_ipfrag_time: 1
ipv4_ipfrag_high_thresh: 134217728
netcore_rmem_max: 2147483647
netcore_wmem_max: 2147483647

# greengrass user/group
ggc_user_uid: 919
ggc_group_gid: 929

# netplan
netplan_files: netplan/99-autoware.x2.yaml

# nftables
nftables_conf_file: nftables/nftables.conf

# otaclient
otaclient_release_version: v3.10.1
otaclient_package_whl_checksum: sha256:6ffa42a92cb964f5bbe57dd7498e9b7994e7598ed7872351a8372a0c9c0a8689
otaclient_manifest_checksum: sha256:41c02224951b1d0cb04c1538a149c45458db1dc39179eb26931bb67288049028
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2.j2
