# cSpell:ignore rexmit

# cyclonedds
cyclonedds:
  network_interface:
    - { address: enp5s0f1, priority: 1 } # Prioritize 10Gb interface
    - { address: vlan.500, priority: 0 }
  minimum_socket_receive_buffer_size: 100MB
  minimum_socket_send_buffer_size: 10MB
  max_message_size: 8950B
  fragment_size: 8850B
  max_rexmit_message_size: 8950B
  water_mark_whc_high: 4MB
  water_mark_whc_low: 10kB
  lease_duration: 120s
  spdp_interval: 90s
ipv4_ipfrag_time: 1
ipv4_ipfrag_high_thresh: 134217728
netcore_rmem_max: 2147483647
netcore_wmem_max: 2147483647

# greengrass user/group
ggc_user_uid: 919
ggc_group_gid: 929

# netplan
netplan_files: netplan/99-autoware.x2.yaml

# nftables
nftables_conf_file: nftables/nftables.conf

# otaclient
otaclient_release_version: v3.13.0
otaclient_package_whl_checksum: sha256:00831b0572a5be33a2349f7865da06d31e514be2d411bd95d89c9f19b25b5996
otaclient_manifest_checksum: sha256:ff002837125cfb9b20df11badc107d8bbd98fafe5b2d0710992d5d712c5b9cb1
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2.j2
