# cSpell:ignore rexmit nocaps

# ========== common ==========
daemon_reload: "{{ reload_systemd | default('yes') }}"
ros_domain_id: 1
autoware_env_dir: "{{ ansible_env.HOME }}"
autoware_env_dir_privileged: false

# ========== ecu_common.yaml ==========

# cyclonedds
cyclonedds:
  network_interface_address:
    - lo
  minimum_socket_receive_buffer_size: 20MB
  minimum_socket_send_buffer_size: default
  max_message_size: 65500B
  fragment_size: 4000B
  max_rexmit_message_size: 1456B # Default value from CycloneDDS documentation # cspell:disable-line
  water_mark_whc_high: 500kB # Default value from CycloneDDS documentation
  water_mark_whc_low: 1kB # Default value from CycloneDDS documentation
ipv4_ipfrag_high_thresh: 268435456

# greengrass user/group
ggc_user_uid: 919
ggc_group_gid: 929

# netplan
netplan_files: netplan/99-autoware.yaml

# nftables
nftables_conf_file: nftables/nftables.conf

# otaclient: sample setup for single ECU
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.j2
# otaclient_logger, for single ECU
otaclient_logger_listen_address: 127.0.0.1

# set-autoware-env
autoware_install_dir: /home/autoware/pilot-auto
vehicle_id: default
vehicle_model: lexus
sensor_model: aip_xx1

# timezone
timezone: Asia/Tokyo

# ========== ecu_develop.yaml ==========

# additional-fonts
additional_font_packages:
  - fonts-noto-cjk

# keyboard: Select keyboard.jp, keyboard.jp+ctrl_nocaps or keyboard.us+ctrl_nocaps
keyboard_layout_file: keyboard.jp+ctrl_nocaps

# ========== ecu_setup.yaml ==========

# sample_role
sample_role_msg: This is sample role world!
