# cSpell:ignore rexmit nocaps ipaddr maxsize

# ========== common ==========
daemon_reload: "{{ reload_systemd | default('yes') }}"
ros_domain_id: 1
autoware_env_dir: "{{ ansible_env.HOME }}"
autoware_env_dir_privileged: false

# ========== ecu_common.yaml ==========

# cyclonedds
cyclonedds:
  network_interface_address:
    - eno1
    - enp5s0
    - enp2s0f0
  minimum_socket_receive_buffer_size: 20MB
  minimum_socket_send_buffer_size: default
  max_message_size: 65500B
  fragment_size: 4000B
  max_rexmit_message_size: 1456B # Default value from CycloneDDS documentation # cspell:disable-line
  water_mark_whc_high: 500kB # Default value from CycloneDDS documentation
  water_mark_whc_low: 1kB # Default value from CycloneDDS documentation
ipv4_ipfrag_high_thresh: 268435456

# greengrass user/group
ggc_user_uid: 919
ggc_group_gid: 929

# netplan
netplan_files: netplan/99-autoware.yaml

# nftables
nftables_conf_file: nftables/nftables.conf

# otaclient: sample setup for single ECU
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.j2
# otaclient_logger, for single ECU
otaclient_logger_listen_address: 127.0.0.1

# set-autoware-env
autoware_install_dir: /home/autoware/pilot-auto.x2
vehicle_id: default
vehicle_model: j6_gen1
sensor_model: aip_x2

# timezone
timezone: Asia/Tokyo

# ========== ecu_develop.yaml ==========

# additional-fonts
additional_font_packages:
  - fonts-noto-cjk

# keyboard: Select keyboard.jp, keyboard.jp+ctrl_nocaps or keyboard.us+ctrl_nocaps
keyboard_layout_file: keyboard.jp+ctrl_nocaps

# ========== ecu_setup.yaml ==========

# pcan
peak_can_mini_pcie:
  - device: pcan0 # VCU
    rule: SUBSYSTEMS=="pci", ATTR{dev_id}=="0x0"
    bitrate: 500000
  - device: pcan1 # IMU
    rule: SUBSYSTEMS=="pci", ATTR{dev_id}=="0x1"
    bitrate: 500000
  - device: pcan2 # Radar: front_center
    rule: SUBSYSTEMS=="usb", ATTR{dev_id}=="0x0", KERNELS=="*.1*"
    bitrate: 500000
  - device: pcan3 # Radar: left_front
    rule: SUBSYSTEMS=="usb", ATTR{dev_id}=="0x1", KERNELS=="*.1*"
    bitrate: 500000
  - device: pcan4 # Radar: left_rear
    rule: SUBSYSTEMS=="usb", ATTR{dev_id}=="0x0", KERNELS=="*.2*"
    bitrate: 500000
  - device: pcan5 # Radar: rear_center
    rule: SUBSYSTEMS=="usb", ATTR{dev_id}=="0x1", KERNELS=="*.2*"
    bitrate: 500000
  - device: pcan6 # Radar: right_rear
    rule: SUBSYSTEMS=="usb", ATTR{dev_id}=="0x0", KERNELS=="*.3*"
    bitrate: 500000
  - device: pcan7 # Radar: right_front
    rule: SUBSYSTEMS=="usb", ATTR{dev_id}=="0x1", KERNELS=="*.3*"
    bitrate: 500000
  - device: pcan8 # EBS
    rule: SUBSYSTEM=="net", ATTRS{idProduct}=="000c", ATTRS{idVendor}=="0c72"
    bitrate: 250000

# ptp4l
ptp4l_master_ports:
  - enp3s0
  - enp4s0
  - enp5s0
  - enp2s0f0
  - eno1

# syslog collector - client
syslog_collector_type: Client
rsyslog_server_ipaddr: 192.168.10.21 # x2-sub
# rsyslog_server_port: 514
# rsyslog_protocol: tcp
rsyslog_queue_maxsize: 1g
