# cSpell:ignore rexmit

# cyclonedds
cyclonedds:
  network_interface:
    - { address: enp5s0f1, priority: 1 } # Prioritize 10Gb interface
    - { address: vlan.500, priority: 0 }
  minimum_socket_receive_buffer_size: 100MB
  minimum_socket_send_buffer_size: 10MB
  max_message_size: 8950B
  fragment_size: 8850B
  max_rexmit_message_size: 8950B
  water_mark_whc_high: 4MB
  water_mark_whc_low: 10kB
  lease_duration: 120s
  spdp_interval: 90s
ipv4_ipfrag_time: 1
ipv4_ipfrag_high_thresh: 134217728
netcore_rmem_max: 2147483647
netcore_wmem_max: 2147483647

# greengrass user/group
ggc_user_uid: 919
ggc_group_gid: 929

# netplan
netplan_files: netplan/99-autoware.x2.yaml

# nftables
nftables_conf_file: nftables/nftables.conf

# otaclient
otaclient_release_version: v3.13.2
otaclient_package_whl_checksum: sha256:84c714886d8c17add0ed6e613a753274f017a4476b20784609117299ddfc75a7
otaclient_manifest_checksum: sha256:83083c803296985ad7b116f5194ea95131756f2cd87308e7d5dc9347914145dd
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2.j2
