# cSpell:ignore ipaddr maxsize

# syslog collector - client
syslog_collector_type: Client
rsyslog_server_ipaddr: 192.168.30.71 # X2 Logging ECU
rsyslog_queue_maxsize: 1g

# rsyncd - server for logpacker coredump plugin
# rsyncd - add systemd-tmpfiles configuration for logpacker coredump plugin
setup_coredump_rsyncd_service: true
rsyncd_hosts_allow: 192.168.30.71 # X2 Logging ECU
setup_coredump_tmpfiles_service: true

# boot shutdown
boot_shutdown_tools_clone_dir: "{{ autoware_install_dir }}/src/product/boot_shutdown_tools"
# boot shutdown manager
# use parameter file in pilot-auto repository
boot_shutdown_manager_param_file: boot_shutdown_manager/boot_shutdown_manager.param.yaml

# configure marvell switch
x2_configure_marvell_switch_board_config_file: bd_cfg_main.xml
x2_configure_marvell_switch_file: X2_J6_Gen2_Main_Marvell.xml

# ptp4l
x2_ptp4l_ecu: main

# redundancy switcher
redundancy_switcher_repository_url: git@github.com:tier4/redundancy_switcher.git
redundancy_switcher_clone_dir: /tmp/redundancy_switcher
redundancy_switcher_version: v4.3.0
redundancy_switcher_install_dir: /opt/redundancy_switcher/bin
redundancy_switcher_conf_install_dir: /opt/redundancy_switcher/conf
redundancy_switcher_conf_files: redundancy_switcher/node_info.yaml
redundancy_switcher_service_template: redundancy_switcher.service.jinja2
node_id: 0

# letterbox_monitor
letterbox_monitor:
  - service_name: default
    ros_log_dir: /home/autoware/.ros/log
    user_name: autoware
    group_name: autoware
    use_call_diag: false
    use_letterbox: true
    ignore_node_names: []
  - service_name: autoware
    ros_log_dir: /home/autoware/.ros/autoware_log
    user_name: autoware
    group_name: autoware
    use_call_diag: true
    use_letterbox: true
    ignore_node_names: []
  - service_name: autoware_system
    ros_log_dir: /home/autoware/.ros/autoware_system_log
    user_name: autoware
    group_name: autoware
    use_call_diag: true
    use_letterbox: true
    ignore_node_names: []

# simple_system_launch
simple_system_launch_items:
  # autoware_launch
  - file: simple_system_launch/autoware_launch.service
    command: |
      mkdir -p /home/autoware/.ros/autoware_log
      export ROS_LOG_DIR=/home/autoware/.ros/autoware_log
      ros2 launch autoware_launch autoware.launch.xml \
              map_path:=/opt/autoware/maps \
              lanelet2_map_file:=lanelet2_map.osm \
              pointcloud_map_file:=pcd \
              vehicle_model:="$VEHICLE_MODEL" \
              sensor_model:="$SENSOR_MODEL" \
              launch_system:=false \
              rviz:=false 2>&1 | tee "$HOME"/autoware.log

  # system
  - file: simple_system_launch/autoware_system_launch.service
    command: |
      mkdir -p /home/autoware/.ros/autoware_system_log
      export ROS_LOG_DIR=/home/autoware/.ros/autoware_system_log
      ros2 launch autoware_launch tier4_system_component.launch.xml \
            system_run_mode:=online \
            launch_system_monitor:=true \
            launch_dummy_diag_publisher:=false \
            sensor_model:="$SENSOR_MODEL" 2>&1 | tee "$HOME"/autoware_system.log

# fool proof check service
check_target_service: autoware_system_launch.service
ecu_type: main
fool_proof_check_network_interface: enp5s0f1 # TODO: check vlan.500

# tier4_service_standby_wait
service_list_for_tier4_system: |
  ptp4l@enp3s0.service \
  ptp4l@vlan.500.service \
  ptp4l_hw_timestamp@vlan.500.service
service_list_for_tier4_autoware: |
  fool_proof_check.service \
  emergency-vehicle-detector.service \
  boot_shutdown.service \
  boot-shutdown-manager.service \
  letterbox_monitor@autoware.service \
  letterbox_monitor@autoware_system.service \
  letterbox_monitor@default.service \
  tier4_system_standby_wait.target

# disable services
# cspell:ignore runlevel utmp
disable_service_list:
  - snapd.apparmor.service
  - snapd.socket
  - snapd.service
  - snapd.seeded.service
  - systemd-update-utmp-runlevel.service
  - update-notifier-download.timer
  - update-notifier-motd.timer
  - motd-news.timer
  - dpkg-db-backup.timer
  - apt-daily-upgrade.timer
  - apt-daily.timer

# scheduling settings
scheduling_settings_autoware_yaml_file: scheduling_settings/scheduling_settings_autoware.yaml
scheduling_settings_others_yaml_file: scheduling_settings/scheduling_settings_others.yaml

# tc_bandwidth_limit
tc_interface: enp5s0f1
