autoware_env_dir_privileged: false
autoware_env_dir: "{{ ansible_env.HOME }}"
autoware_install_dir: "{{ ansible_env.HOME }}/pilot-auto.x2"
daemon_reload: "{{ reload_systemd | default('yes') }}"
ros_domain_id: 1
sensor_model: aip_x2_gen2
timezone: Asia/Tokyo
vehicle_id: default
vehicle_model: j6_gen2

# boot shutdown
boot_shutdown_tools_repository: https://github.com/tier4/boot_shutdown_tools.git
boot_shutdown_tools_version: v0.3.2
boot_shutdown_service_config_file: boot_shutdown_service/boot_shutdown.param.yaml

# cert setup
run_cert_setup: false

# ros_distro
ros_distro: humble

# SYNC.TOOLING
sync_tooling_version: v0.2.5
