# usbguard
usbguard_rules_file: usbguard/rules.x2-main.conf

# third_party_kernel_module_sign
kernel_module_sign_key_repository: git@github.com:tier4/x2-key
kernel_module_sign_private_key_file: third_party_kernel_module_sign/x2_private_key.pem
kernel_module_sign_cert_file: third_party_kernel_module_sign/x2_cert.der

# nftables
nftables_conf_file: nftables/nftables.conf
