# cspell: ignore mincho rexmit ipaddr maxsize nocaps netcore wmem
# common
daemon_reload: "{{ reload_systemd | default('yes') }}"
ros_domain_id: 1
rosbag_logging_directory: /mnt/ROSBAG
systemctl_default: multi-user.target
autoware_env_dir: "{{ ansible_env.HOME }}"
autoware_env_dir_privileged: false

# timezone
timezone: Asia/Tokyo

# additional-fonts
additional_font_packages:
  - fonts-noto-cjk
  - fonts-takao-mincho

# boot_shutdown_interface
boot_shutdown_interface_param_file: empty_topic_boot_shutdown.param.yaml

# cyclonedds
cyclonedds:
  network_interface:
    - { address: enp3s0f0, priority: default }
    - { address: enp8s0, priority: default }
  minimum_socket_receive_buffer_size: 10MB
  minimum_socket_send_buffer_size: 10MB
  max_message_size: 8950B
  fragment_size: 8850B
  max_rexmit_message_size: 8950B
  water_mark_whc_high: 4MB
  water_mark_whc_low: 10kB
ipv4_ipfrag_time: 1
ipv4_ipfrag_high_thresh: 134217728
netcore_rmem_max: 2147483647
netcore_wmem_max:
  2147483647

  # keyboard
keyboard_layout_file: keyboard.jp+ctrl_nocaps

# ptp4l port
ptp4l_network_port: enp8s0

# simple-system-launch
# TODO: The *.*.* will change to the release version in future
simple_system_launch_command: /opt/mot/build/MaintenanceOperationTool-*.*.*.AppImage
simple_system_service_file: mot.service

# netplan
netplan_files: netplan/99-autoware.x2-logging.yaml

# otaclient
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2-logging
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2-10gbe.j2

# boot_shutdown
boot_shutdown_service_root: /opt/mot/msg/install/boot_shutdown_service

# log
log_storage_period: -1 month
target_remove_log_dirs:
  - /opt/mot/logs/*
  - /home/autoware/.config/MaintenanceOperationTool/logs/*

# autoware logging suite
# - logpacker
logpacker_config_template: logpacker/logpacker_config_x2.yaml.jinja2
# - logpacker - syslog plugin
logpacker_enable_syslog_plugin: true
# - logpacker - rosbag plugin
logpacker_enable_rosbag_plugin: true
qos_profile_overrides_template: logpacker/qos_profile_overrides_x2.yaml
# - bagtaker
rosbag_copy_directory: /media/autoware/ROSBAG
bagtaker_params_template: bagtaker2/bagtaker_params_x2.yaml.jinja2

# set-autoware-env
autoware_install_dir: /home/autoware/pilot-auto.x2
vehicle_id: default
vehicle_model: j6_gen2
sensor_model: aip_x2_gen2

# mot_env_setup
mot_install_dir: "{{ ansible_env.HOME }}/OperationMaintenanceTool"
replace_install_setup_bash: false
bridge_ip_address: 127.0.0.1
fms_agent_ip_address: 192.168.30.11
zoom_level: 1
