# cspell: ignore mincho rexmit ipaddr maxsize nocaps netcore wmem pactl
# common
rosbag_logging_directory: /mnt/ROSBAG
systemctl_default: multi-user.target

# additional-fonts
additional_font_packages:
  - fonts-noto-cjk
  - fonts-takao-mincho

# cyclonedds
cyclonedds:
  network_interface:
    - { address: enp3s0f0, priority: 1 } # Prioritize 10Gb interface
    - { address: enp8s0, priority: 0 }
  minimum_socket_receive_buffer_size: 10MB
  minimum_socket_send_buffer_size: 10MB
  max_message_size: 8950B
  fragment_size: 8850B
  max_rexmit_message_size: 8950B
  water_mark_whc_high: 4MB
  water_mark_whc_low: 10kB
  lease_duration: 10s
  spdp_interval: 8s
ipv4_ipfrag_time: 1
ipv4_ipfrag_high_thresh: 134217728
netcore_rmem_max: 2147483647
netcore_wmem_max:
  2147483647

  # keyboard
keyboard_layout_file: keyboard.jp+ctrl_nocaps

# ptp4l port
ptp4l_network_port: enp8s0
ptp4l_use_software_stamp: false
ptp4l_synchronize_system_clock: true
ptp4l_phc2sys_offset: -37

# SYNC.TOOLING
sync_tooling:
  worker:
    ptp4l_units:
      - ptp4l
    phc2sys_units:
      - phc2sys

# rsyncd
setup_systemd_analyze_collector: true
# systemd_analyze_collector
use_rsync_send: false # logging ECU does not need rsync to send data
# param_diff_uploader
is_param_diff_collector: true

# netplan
netplan_files: netplan/99-autoware.x2-logging.yaml

# otaclient
otaclient_release_version: v3.13.0
otaclient_package_whl_checksum: sha256:00831b0572a5be33a2349f7865da06d31e514be2d411bd95d89c9f19b25b5996
otaclient_manifest_checksum: sha256:ff002837125cfb9b20df11badc107d8bbd98fafe5b2d0710992d5d712c5b9cb1
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2-logging
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2-10gbe.j2

# log
log_storage_period: -1 month
target_remove_log_dirs:
  - /opt/mot/logs/*
  - /home/autoware/.config/MaintenanceOperationTool/logs/*

# autoware logging suite
autoware_logging_suite_version: v0.10.3
autoware_logging_suite_modules:
  - autoware_logging_msgs
  - logpacker
  - bagkeeper
  - bagkeeper_interfaces
  - bagrollbacker
  - bagtaker
  - dssad_packer
  - rosbag_data_checker
  - tier4_logging_event_trigger_panel
  - tier4_logging_dummy_hazard_panel
# - logpacker
logpacker_config_template: logpacker/logpacker_config.yaml.jinja2
# - logpacker - syslog plugin
logpacker_enable_syslog_plugin: true
# - logpacker - rosbag plugin
logpacker_enable_rosbag_plugin: true
qos_profile_overrides_template: logpacker/qos_profile_overrides.yaml
# - bagtaker
rosbag_copy_directory: /media/autoware/ROSBAG
bagtaker_params_template: bagtaker2/bagtaker_params_x2.yaml.jinja2
# - bagkeeper
bagkeeper_params_template: bagkeeper/bagkeeper_params_x2.yaml.jinja2
# - bagrollbacker
bagrollbacker_param_template: bagrollbacker/bagrollbacker_params_x2.yaml.jinja2
# rsyncd - add systemd-tmpfiles configuration for logpacker coredump plugin
setup_coredump_rsyncd_service: false
setup_coredump_tmpfiles_service: true

# boot_shutdown
boot_shutdown_tools_clone_dir: "{{ autoware_install_dir }}/src/product/boot_shutdown_tools"
boot_shutdown_manager_param_file: boot_shutdown_manager/boot_shutdown_manager.param.yaml
boot_shutdown_service_config_file: boot_shutdown_service/boot_shutdown.param.logging.yaml
boot_shutdown_service_script_src_path: boot_shutdown_service/shutdown.logging.sh

# mot_env_setup
mot_repository_version_humble: 7f38b2b108f59b2b3a668271f9a93785fbbc8f22 # beta/v4.3.1
mot_install_dir: "{{ ansible_env.HOME }}/OperationMaintenanceTool"
mot_run_command: "pactl set-sink-volume $(pactl list sinks | awk '/Name: / && /YunChen_Technology_USB_Composite_Device/ {print $2}') 100% && /opt/mot/build/MaintenanceOperationTool-*.*.*.AppImage"
depends_node_version: v20.18.1
replace_install_setup_bash: false
bridge_ip_address: 127.0.0.1
fms_agent_ip_address: 192.168.30.11
zoom_level: 1
mot_vehicle_model: j6-gen2
mot_error_messages: mrm_messages/mrm_messages.json

# release_rosbag_page_cache
release_page_cache_threshold_second_from: 65
release_page_cache_threshold_second_to: 130
release_page_cache_timer: minutely

# pyrocan
pyrocan_interface: pcan1
pyrocan_after_this_service: can-logging.service

# MOB Proxy
logagent_mob_proxy_address: 192.168.20.11:18090
# autoware_logging_suite/logagent
logagent_config_template: logagent/logagent_config_x2.yaml.jinja2
logagent_logging_suite_version: "{{ autoware_logging_suite_version }}"
# logagent upload log
logagent_libcurl: true
logagent_log_upload_max_file_size_mb: 128
logagent_syslog_upload_max_file_size_mb: "{{ logagent_log_upload_max_file_size_mb }}"
# logging directory
logagent_rosbag_logging_directory: "{{ rosbag_logging_directory }}"
logagent_rosbag_logging_directory_mountpoint: "{{ logagent_rosbag_logging_directory }}"

# fool proof check service
fool_proof_check: true
check_target_service: logpacker.service
ecu_type: logging
fool_proof_check_network_interface: enp3s0f0
# # letterbox_monitor
# letterbox_monitor:
#   - service_name: default
#     ros_log_dir: /home/autoware/.ros/log
#     user_name: autoware
#     group_name: autoware
#     use_call_diag: false
#     use_letterbox: false
#     ignore_node_names: []

# simple system launch
simple_system_launch_items:
  - file: simple_system_launch/vehicle_info_monitor.service
    command: |
      STOP_STATUS=("in_progress" "failure")
      LOGGING_MODE="/etc/autoware_logging_suite/logpacker/logging_mode"
      TARGET_VALUE="event"
      prev_status=""

      ros2 topic echo -f /webauto/vehicle_info |
      while read -r line; do

        json=$(echo "$line" | sed -n "s/^data: '\(.*\)'$/\1/p")
        if [ -z "$json" ]; then
          continue
        fi

        current_status=$(echo "$json" | jq -r '.firmware_deployment_status')

        if [ ! -f "$LOGGING_MODE" ]; then
          echo "File not found: $LOGGING_MODE"
          continue
        fi

        if [ "$(cat "$LOGGING_MODE")" = "$TARGET_VALUE" ]; then
          if [[ -n "$current_status" && "$current_status" != "$prev_status" ]]; then
            echo "firmware_deployment_status changed: $prev_status -> $current_status"

            if [[ " ${STOP_STATUS[*]} " == *" $current_status "* ]]; then
              systemctl is-active --quiet bagkeeper.service && systemctl stop bagkeeper.service
            else
              ! systemctl is-active --quiet bagkeeper.service && systemctl start bagkeeper.service
            fi

            prev_status="$current_status"
          fi
        fi
      done

# tier4_service_standby_wait
service_list_for_tier4_system: ptp4l.service
service_list_for_tier4_autoware: |
  fool-proof-check.service \
  boot-shutdown.service \
  tier4_system_standby_wait.target
network_interface_for_tier4_service_standby_wait: enp3s0f0
# disable services
# cspell:ignore runlevel utmp
disable_system_service_list:
  - systemd-update-utmp-runlevel.service
  - update-notifier-download.timer
  - update-notifier-motd.timer
  - motd-news.timer
  - dpkg-db-backup.timer
  - apt-daily-upgrade.timer
  - apt-daily.timer

### metric_agent
# metric_agent node parameters
metric_agent_rate_in_hertz: 10
metric_agent_pubs_rate_in_hertz: 10
metric_agent_subs_rate_in_hertz: 10

# metric_agent config
metric_agent_version: 2a64b8ccc5e042ca87abaa692205f18da8ba3d77 # develop # Future references will be by tags or SHAs.
metric_agent_params_template: metric_agent/metric_agent_params_x2.yaml.jinja2
metric_agent_config_template: metric_agent/metric_agent_config_uds_x2.yaml.jinja2
metric_agent_product_config_template: metric_agent/product_metric_config_x2.yaml.jinja2 # If you want to manage all metrics derived from specific topic-type topics
# metric_agent_product_metric_list: /vars/x2_product_metric_list.yaml # If you only want to product common metrics

# telegraf config for metric_agent
metric_agent_telegraf_service_config_template: metric_agent/telegraf.socket_listener_uds_x2.conf.jinja2
metric_agent_telegraf_hostname: logging_ecu
metric_agent_telegraf_otel_hostname: ${AGENT_HOSTNAME}

# set_autoware_env
vehicle_id: INVALID_VEHICLE_ID

# set services' order
sync_tooling_wait_for_services:
  - tier4_ros2_standby_wait.target
bagkeeper_wait_for_services:
  - tier4_autoware_standby_wait.target
bagtaker_wait_for_services:
  - tier4_autoware_standby_wait.target
logagent_wait_for_services:
  - tier4_autoware_standby_wait.target
logpacker_wait_for_services:
  - tier4_autoware_standby_wait.target
mot_wait_for_services:
  - tier4_autoware_standby_wait.target
metric_agent_wait_for_services:
  - tier4_autoware_standby_wait.target
  - tier4_system_standby_wait.target
rosbag_watchdog_wait_for_services:
  - tier4_autoware_standby_wait.target
