# cspell: ignore mincho rexmit ipaddr maxsize nocaps netcore wmem
# common
rosbag_logging_directory: /mnt/ROSBAG
systemctl_default: multi-user.target

# additional-fonts
additional_font_packages:
  - fonts-noto-cjk
  - fonts-takao-mincho

# cyclonedds
cyclonedds:
  network_interface:
    - { address: enp3s0f0, priority: default }
    - { address: enp8s0, priority: default }
  minimum_socket_receive_buffer_size: 10MB
  minimum_socket_send_buffer_size: 10MB
  max_message_size: 8950B
  fragment_size: 8850B
  max_rexmit_message_size: 8950B
  water_mark_whc_high: 4MB
  water_mark_whc_low: 10kB
ipv4_ipfrag_time: 1
ipv4_ipfrag_high_thresh: 134217728
netcore_rmem_max: 2147483647
netcore_wmem_max:
  2147483647

  # keyboard
keyboard_layout_file: keyboard.jp+ctrl_nocaps

# ptp4l port
ptp4l_network_port: enp8s0

# netplan
netplan_files: netplan/99-autoware.x2-logging.yaml

# otaclient
otaclient_release_version: v3.9.1
otaclient_package_whl_checksum: sha256:ca42c170ff08b41f0b5595488e699a419cf6bce909e9a44b9e8f5da39b6908c5
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2-logging
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2-10gbe.j2

# log
log_storage_period: -1 month
target_remove_log_dirs:
  - /opt/mot/logs/*
  - /home/autoware/.config/MaintenanceOperationTool/logs/*

# autoware logging suite
autoware_logging_suite_version: v0.8.3
autoware_logging_suite_modules:
  - autoware_logging_msgs
  - logpacker
  - bagkeeper
  - bagkeeper_interfaces
  - bagrollbacker
  - bagtaker
  - dssad_packer
  - rosbag_data_checker
  - tier4_logging_event_trigger_panel
  - tier4_logging_dummy_hazard_panel
# - logpacker
logpacker_config_template: logpacker/logpacker_config_x2.yaml.jinja2
# - logpacker - syslog plugin
logpacker_enable_syslog_plugin: true
# - logpacker - rosbag plugin
logpacker_enable_rosbag_plugin: true
qos_profile_overrides_template: logpacker/qos_profile_overrides_x2.yaml
# - bagtaker
rosbag_copy_directory: /media/autoware/ROSBAG
bagtaker_params_template: bagtaker2/bagtaker_params_x2.yaml.jinja2
# - bagkeeper
bagkeeper_params_template: bagkeeper/bagkeeper_params_x2.yaml.jinja2
# - bagrollbacker
bagrollbacker_param_template: bagrollbacker/bagrollbacker_params_x2.yaml.jinja2

# boot_shutdown
build_boot_shutdown_api_msgs: true
boot_shutdown_tools_clone_dir: "{{ autoware_install_dir }}/src/product/boot_shutdown_tools"
boot_shutdown_service_config_file: boot_shutdown_service/boot_shutdown.param.logging.yaml
boot_shutdown_service_script_src_path: boot_shutdown_service/shutdown.logging.sh

# mot_env_setup
mot_repository_version_humble: 414ebc046ab06411ace803d16ca21523bfed1e97 # beta/v4.2.0
mot_install_dir: "{{ ansible_env.HOME }}/OperationMaintenanceTool"
depends_node_version: v20.18.1
replace_install_setup_bash: false
bridge_ip_address: 127.0.0.1
fms_agent_ip_address: 192.168.30.11
zoom_level: 1
mot_vehicle_model: j6-gen2

# release_rosbag_page_cache
release_page_cache_threshold_second_from: 65
release_page_cache_threshold_second_to: 130
release_page_cache_timer: minutely

# pyrocan
pyrocan_interface: pcan1
pyrocan_after_this_service: can-logging.service

# MOB Proxy
logagent_mob_proxy_address: 192.168.20.11:18090
# autoware_logging_suite/logagent
logagent_config_template: logagent/logagent_config_x2.yaml.jinja2
logagent_logging_suite_version: v0.8.3
# logging directory
logagent_rosbag_logging_directory: "{{ rosbag_logging_directory }}"
logagent_rosbag_logging_directory_mountpoint: "{{ logagent_rosbag_logging_directory }}"

# fool proof check service
fool_proof_check: true
check_target_service: logpacker.service
ecu_type: logging
fool_proof_check_network_interface: enp3s0f0
# # letterbox_monitor
# letterbox_monitor:
#   - service_name: default
#     ros_log_dir: /home/autoware/.ros/log
#     user_name: autoware
#     group_name: autoware
#     use_call_diag: false
#     use_letterbox: false
#     ignore_node_names: []

# simple system launch
simple_system_launch_items:
  - file: simple_system_launch/vehicle_info_monitor.service
    command: |
      STOP_STATUS=("in_progress" "failure")
      LOGGING_MODE="/etc/autoware_logging_suite/logpacker/logging_mode"
      TARGET_VALUE="event"
      prev_status=""

      ros2 topic echo -f /webauto/vehicle_info |
      while read -r line; do

        json=$(echo "$line" | sed -n "s/^data: '\(.*\)'$/\1/p")
        if [ -z "$json" ]; then
          continue
        fi

        current_status=$(echo "$json" | jq -r '.firmware_deployment_status')

        if [ ! -f "$LOGGING_MODE" ]; then
          echo "File not found: $LOGGING_MODE"
          continue
        fi

        if [ "$(cat "$LOGGING_MODE")" = "$TARGET_VALUE" ]; then
          if [[ -n "$current_status" && "$current_status" != "$prev_status" ]]; then
            echo "firmware_deployment_status changed: $prev_status -> $current_status"

            if [[ " ${STOP_STATUS[*]} " == *" $current_status "* ]]; then
              systemctl is-active --quiet bagkeeper.service && systemctl stop bagkeeper.service
            else
              ! systemctl is-active --quiet bagkeeper.service && systemctl start bagkeeper.service
            fi

            prev_status="$current_status"
          fi
        fi
      done
