# cspell: ignore dustynv ipaddr libpython maxsize rexmit compat
# common
is_in_docker: "{{ daemon_reload == 'no' }}"

autoware_env_dir: /opt/autoware/env
autoware_env_dir_privileged: true
xx1_logging_ecu: false

# syslog collector - client
syslog_collector_type: Client
# rsyslog_server_ipaddr: 192.168.30.11 # x2
rsyslog_server_ipaddr: 192.168.30.71 # X2 Logging ECU
# rsyslog_server_port: 514
# rsyslog_protocol: tcp
rsyslog_queue_maxsize: 1g

# iptables
iptables_ipv4_conf_file: iptables/rules.x2.media-streaming.v4
iptables_ipv6_conf_file: iptables/rules.x2.media-streaming.v6
# nftables (media streaming ECU uses iptables)
# nftables_conf_file: nftables.x2-media-streaming.conf

# otaclient
otaclient_release_version: v3.8.4
otaclient_package_whl_checksum: sha256:c118f7ce69bce85b7a038dd7829ca8567f665cf8f86772a6e773e77ac3b3e8fe
# otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2-media-streaming
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2-1gbe.j2
# otaclient_bionic_compat: true

# media_streaming
media_streaming:
  install_docker: false
  required_python: python3.8
  required_libpython: libpython3.8
