# cspell: ignore dustynv
# common
daemon_reload: "{{ reload_systemd | default('yes') }}"

# boot_shutdown_docker
boot_shutdown_docker_base: dustynv/ros:galactic-ros-base-l4t-r32.6.1
boot_shutdown_docker_name: ghcr.io/tier4/object-recognition:x2
