# cSpell:ignore rexmit nocaps ipaddr maxsize

# cyclonedds
# NOTE: Cyclonedds settings for Sub ECU is not determined yet. Only 1GbE interface is used for now.
cyclonedds:
  network_interface:
    - { address: enp5s0f0, priority: default }
  minimum_socket_receive_buffer_size: 20MB
  minimum_socket_send_buffer_size: default
  max_message_size: 65500B
  fragment_size: 4000B
  max_rexmit_message_size: 1456B
  water_mark_whc_high: 500kB
  water_mark_whc_low: 1kB
ipv4_ipfrag_time: 1
ipv4_ipfrag_high_thresh: 134217728
netcore_rmem_max: 2147483647
netcore_wmem_max: 2147483647

# x2_cyclonedds_for_redundancy
x2_cyclonedds_for_redundancy_cyclonedds:
  network_interface:
    - { address: enp5s0f1, priority: 1 } # Prioritize 10Gb interface
    - { address: enp5s0f0, priority: 0 }
  minimum_socket_receive_buffer_size: 20MB
  minimum_socket_send_buffer_size: default
  max_message_size: 65500B
  fragment_size: 4000B
  max_rexmit_message_size: 1456B
  water_mark_whc_high: 500kB
  water_mark_whc_low: 1kB

# netplan
netplan_files: netplan/99-autoware.x2-sub.yaml

# otaclient
otaclient_release_version: v3.8.4
otaclient_package_whl_checksum: sha256:c118f7ce69bce85b7a038dd7829ca8567f665cf8f86772a6e773e77ac3b3e8fe
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2-sub
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2-1gbe.j2

# ========== ecu_setup.yaml ==========

# syslog collector - client
syslog_collector_type: Client
# rsyslog_server_ipaddr: 192.168.30.71 # X2 Logging ECU (10GB Eth)
rsyslog_server_ipaddr: 192.168.20.71 # X2 Logging ECU (1GB Eth)
rsyslog_queue_maxsize: 1g

# rsyncd - server for logpacker coredump plugin
# rsyncd - add systemd-tmpfiles configuration for logpacker coredump plugin
setup_coredump_rsyncd_service: true
# rsyncd_hosts_allow: 192.168.30.71 # X2 Logging ECU (10GB Eth)
rsyncd_hosts_allow: 192.168.20.71 # X2 Logging ECU (1GB Eth)
setup_coredump_tmpfiles_service: true

# configure marvell switch
x2_configure_marvell_switch_board_config_file: bd_cfg_sub.xml
x2_configure_marvell_switch_file: X2_J6_Gen2_Sub_Marvell.xml

# ptp4l
x2_ptp4l_ecu: sub

# rviz
rviz_config_path: /home/autoware/autoware.proj/src/autoware/launcher/autoware_launch/rviz/autoware_debug.rviz

# screen_recorder
screen_recorder_default_logging_directory: /tmp
screen_recorder_default_display_variable: :0
screen_recorder_default_service_enabled: false

# redundancy switcher
redundancy_switcher_repository_url: git@github.com:tier4/redundancy_switcher.git
redundancy_switcher_clone_dir: /tmp/redundancy_switcher
redundancy_switcher_version: beta/v4.2
redundancy_switcher_install_dir: /opt/redundancy_switcher/bin
redundancy_switcher_conf_install_dir: /opt/redundancy_switcher/conf
redundancy_switcher_conf_files: redundancy_switcher/node_info.yaml
redundancy_switcher_service_template: redundancy_switcher.service.jinja2
node_id: 1
