# cspell: ignore rexmit
# cyclonedds
cyclonedds:
  network_interface_address:
    - vlan.500
  minimum_socket_receive_buffer_size: 20MB
  minimum_socket_send_buffer_size: default
  max_message_size: 65500B
  fragment_size: 4000B
  max_rexmit_message_size: 1456B # Default value from CycloneDDS documentation
  water_mark_whc_high: 500kB # Default value from CycloneDDS documentation
  water_mark_whc_low: 1kB # Default value from CycloneDDS documentation

# netplan
netplan_files: netplan/99-autoware.x2-signage.vlan.yaml
netplan_old_file: netplan/99-autoware.x2-signage.yaml

# ptp4l port
ptp4l_network_port: vlan.500
