# cspell: ignore ipaddr maxsize pactl rexmit
# common
autoware_install_dir: "{{ ansible_env.HOME }}/vehicle_voice_alert_system"
systemctl_default: multi-user.target

# additional-fonts
additional_font_packages:
  - fonts-noto-cjk

# keyboard
keyboard_layout_file: keyboard.jp

# cyclonedds
cyclonedds:
  network_interface:
    - { address: enp1s0, priority: default }
  minimum_socket_receive_buffer_size: 20MB
  minimum_socket_send_buffer_size: default
  max_message_size: 65500B
  fragment_size: 4000B
  max_rexmit_message_size: 1456B # Default value from CycloneDDS documentation
  water_mark_whc_high: 500kB # Default value from CycloneDDS documentation
  water_mark_whc_low: 1kB # Default value from CycloneDDS documentation
  lease_duration: 120s
  spdp_interval: 90s

# ptp4l port
ptp4l_network_port: enp1s0
ptp4l_use_software_stamp: false
ptp4l_synchronize_system_clock: true
ptp4l_phc2sys_offset: -37

# ros2-app-build
ros2_app_repository: git@github.com:tier4/vehicle_voice_alert_system.git
ros2_app_repository_version: d6e613af70255d37807e1feb659d730af9d9889d # beta/v4.3.1
depends_repos: vehicle_voice_alert_system.repos

# simple system launch
simple_system_launch_items:
  - file: vehicle_sound.service
    command: pactl -- set-sink-volume 0 90%; ros2 launch vehicle_voice_alert_system vehicle_voice_alert_system.launch.xml

# netplan
netplan_files: netplan/99-autoware.x2-voice-system.yaml

# syslog collector
syslog_collector_type: Client
rsyslog_server_ipaddr: 192.168.20.71
rsyslog_queue_maxsize: 1g

# systemd_analyze_collector
rsync_target_host_ip: 192.168.20.71

# otaclient
otaclient_release_version: v3.13.2
otaclient_package_whl_checksum: sha256:84c714886d8c17add0ed6e613a753274f017a4476b20784609117299ddfc75a7
otaclient_manifest_checksum: sha256:83083c803296985ad7b116f5194ea95131756f2cd87308e7d5dc9347914145dd
otaclient_ecu_info_yaml: otaclient/ecu_info.yaml.x2-voice-system
otaclient_proxy_info_yaml: otaclient/proxy_info.yaml.x2-1gbe.j2

# Passenger App
passenger_app_version: v0.0.4

# set_autoware_env
vehicle_id: INVALID_VEHICLE_ID
