# cspell: ignore deploykey sdkkey vicone

x2_xcarbon_ecu_model: Autoware-test
x2_xcarbon_ecu_id: Autoware-test-01
x2_xcarbon_vehicle_model: X2 J6 Gen2
x2_xcarbon_custom_group_id: Autoware-x2
x2_xcarbon_package_name: vicone_xcarbon_5.6.8_ubuntu_22_04_x86_64_tier4.tar.gz
x2_xcarbon_package_path: xcarbon_packages_and_keys/{{ x2_xcarbon_package_name }}
x2_xcarbon_sdkkey_name: customer_key
x2_xcarbon_sdkkey_path: xcarbon_packages_and_keys/{{ x2_xcarbon_sdkkey_name }}
x2_xcarbon_deploykey_name: deployment_key
x2_xcarbon_deploykey_path: xcarbon_packages_and_keys/{{ x2_xcarbon_deploykey_name }}
x2_xcarbon_key_repo: git@github.com:tier4/x2-key.git
x2_xcarbon_key_version: v0.0.1
x2_xcarbon_ker_rel: 5.19.0-50-generic
x2_xcarbon_x2_key_clone_dir: /tmp/x2_key
