---
/**:
  ros__parameters:
    update_rate: 1.0
    startup_timeout: 60.0
    preparation_timeout: 60.0
    topic_port: 10000
    service_timeout: 1
    managed_ecu:
      main:
        primary: true
        service_address: 192.168.20.11
      logging:
        skip_shutdown: true
      perception1:
        service_address: 192.168.20.31
      perception2:
        service_address: 192.168.20.32
      addon-lite:
        service_address: 192.168.20.33
      ms1:
        service_address: 192.168.20.61
      ms2:
        service_address: 192.168.20.62
      signage:
        service_address: 192.168.20.41
      voice_system:
        service_address: 192.168.20.51
      sub:
        service_address: 192.168.20.21
