hostname: media-streaming1
persist_files:
  - /boot/ota/ecu_info.yaml
  - /boot/ota/proxy_info.yaml
  - /etc/hosts
  - /etc/hostname
  - /etc/resolv.conf
  - /etc/dhcpd.conf
  - /etc/line_switcher/config.yml
  - /etc/recording/config.yml
  - /etc/udev/rules.d/99-mkuvcdev.rules
  - /greengrass/config/config.json
  - /greengrass/config/v2_init_config.yaml
  - /greengrass/certs
  - /greengrass/devices
  - /media/docker-compose.yml
  - /media/config
  - /opt/mkuvcdev/mkuvcdev.conf
  - /opt/autoware/env/domain.env
  - /opt/autoware/env/vehicle.env
  - /opt/autoware/env/jetson.env
  - /opt/devtools
