/**:
  ros__parameters:
    startup_timeout: 180
    prepare_shutdown_time: 1
    execute_shutdown_time: 13

    topic_config:
      name: /api/autoware/get/rosbag_record_status
      type: tier4_external_api_msgs/msg/RosbagRecordStatus
      transient_local: false
      best_effort: false

    additional_prepare_shutdown_command:
      [systemctl stop bagpacker.service]
