# cspell: ignore enablehighlevelapi
- name: Setup ECU by common roles
  hosts: localhost
  vars_files:
    - ./vars/ecu_setup.yaml
  vars:
    ros_distro: humble
  roles:
    - { role: autoware.ecu_system_setup.bash_completion }
    - { role: autoware.ecu_system_setup.clean_ros_log }
    - { role: autoware.ecu_system_setup.chrony }
    - { role: autoware.ecu_system_setup.cyclonedds }
    - { role: autoware.ecu_system_setup.edac }
    - { role: autoware.ecu_system_setup.evaluator_self_hosted_environment }
    - { role: autoware.ecu_system_setup.greengrass_dependencies }
    # yamllint disable rule:indentation
    - {
        role: autoware.ecu_system_setup.greengrass_v2,
        when: ansible_distribution_version == "22.04",
      }
    # yamllint enable rule:indentation
    - { role: autoware.ecu_system_setup.hdd_reader }
    - { role: autoware.ecu_system_setup.msr_reader }
    - { role: autoware.ecu_system_setup.netplan }
    - { role: autoware.ecu_system_setup.nftables }
    - { role: autoware.ecu_system_setup.otaclient }
    - { role: autoware.ecu_system_setup.otaclient_logger }
    - { role: autoware.ecu_system_setup.set_autoware_env }
    - { role: autoware.ecu_system_setup.stop_auto_upgrade }
    - { role: autoware.ecu_system_setup.timezone }
    - { role: autoware.ecu_system_setup.touch_enablehighlevelapi }
    - { role: autoware.ecu_system_setup.traffic_reader }
    - { role: autoware.ecu_system_setup.rsyncd }
