# cspell:ignore fintek
- name: Include additional playbook for common
  ansible.builtin.import_playbook: pilot_auto.dev_env.ecu_common

- name: Include playbook for development
  ansible.builtin.import_playbook: pilot_auto.dev_env.ecu_develop

- name: Setup ECU by additional roles
  hosts: localhost
  vars_files:
    - ./vars/essential_vars.yaml
    - ./vars/ecu_setup.yaml
  roles:
    # add your necessary roles
    - { role: autoware.ecu_system_setup.automatic_login }
    - role: autoware.ecu_system_setup.boot_shutdown_service
      when: skip_for_github_actions is not defined or not skip_for_github_actions | bool
    - { role: autoware.ecu_system_setup.disable_services }
    - { role: autoware.ecu_system_setup.ip_routing_policy }
    - { role: autoware.ecu_system_setup.lenovo_keyboard }
    - { role: autoware.ecu_system_setup.ota_first_boot_flag }
    - { role: autoware.ecu_system_setup.rootfs_encrypt }
    - { role: autoware.ecu_system_setup.rsyslog }
    - { role: autoware.ecu_system_setup.syslog_collector_client }
    - { role: autoware.ecu_system_setup.tier4_service_standby_wait }
    - { role: autoware.ecu_system_setup.fintek_can_driver }
    - { role: autoware.ecu_system_setup.marvell_switch_driver }
    - { role: autoware.ecu_system_setup.simple_system_launch } # if you launch autoware as a service, delete comment out
    - { role: autoware.ecu_system_setup.fool_proof_check } # fool proof check for autoware function
    - role: autoware.ecu_system_setup.param_diff_uploader
      when: skip_for_github_actions is not defined or not skip_for_github_actions | bool
    - { role: autoware.ecu_system_setup.letterbox_monitor }
    - role: autoware.ecu_system_setup.build_system_monitor
      when: skip_for_github_actions is not defined or not skip_for_github_actions | bool
    - { role: autoware.ecu_system_setup.redundancy_switcher }
    - role: autoware.ecu_system_setup.domain_bridge
      when: skip_for_github_actions is not defined or not skip_for_github_actions | bool
    - role: autoware.ecu_system_setup.tc_bandwidth_limit
      when: skip_for_github_actions is not defined or not skip_for_github_actions | bool
    - { role: autoware.ecu_system_setup.imu_offset_estimator }
    - { role: autoware.ecu_system_setup.emergency_vehicle_detector }
    - { role: autoware.ecu_system_setup.scheduling_settings_script }
    - role: autoware.ecu_system_setup.sync_tooling
      when: skip_for_github_actions is not defined or not skip_for_github_actions | bool
    # - { role: x2_autoware }
    - { role: x2_can_adm }
    - { role: x2_configure_radar }
    - { role: x2_configure_marvell_switch }
    - { role: x2_ptp4l }
    - { role: x2_dev_tools }
    - { role: x2_cmd_helper_completion }
    - { role: autoware.ecu_system_setup.systemd_analyze_collector }
    - { role: autoware.ecu_system_setup.passenger_app_agent }
    - { role: divert_jetpack_static_lib }
    # TODO: This is temporary change. Delete when applied https://github.com/autowarefoundation/autoware/pull/6475
    - { role: delete_ccache_duplicates }

- name: Conditionally run cert setup
  hosts: localhost
  vars_files:
    - ./vars/essential_vars.yaml
    - ./cert/vars/ecu_setup.yaml
  tasks:
    - name: Run cert setup tasks
      ansible.builtin.include_tasks: cert/ecu_setup.yaml
      when: run_cert_setup | default(false)
