- name: Setup ECU by development roles
  hosts: localhost
  vars_files:
    - ./vars/essential_vars.yaml
    - ./vars/ecu_develop.yaml
  roles:
    - { role: autoware.ecu_system_setup.additional_fonts }
    - { role: autoware.ecu_system_setup.disable_lock_screen }
    - { role: autoware.ecu_system_setup.fzf }
    - { role: autoware.ecu_system_setup.google_chrome }
    - { role: autoware.ecu_system_setup.ibus_mozc }
    - { role: autoware.ecu_system_setup.install_support_gui_tools }
    - { role: autoware.ecu_system_setup.exteverse }
    - { role: x2_deploy_exteverse_config }
    - { role: autoware.ecu_system_setup.keyboard }
    - { role: autoware.ecu_system_setup.vscode }
