- name: Execute x2 master playbook
  ansible.builtin.import_playbook: pilot_auto.dev_env.ecu_setup

- name: Setup x2 cert
  hosts: localhost
  vars_files:
    - ./vars/x2_cert.yaml
  roles:
    - { role: autoware.ecu_system_setup.usbguard }
    - { role: autoware.ecu_system_setup.third_party_kernel_module_sign }
