- name: Setup x2 media streaming
  hosts: localhost
  vars_files:
    - ./vars/x2_media_streaming.yaml
  roles:
    - { role: autoware.ecu_system_setup.boot_shutdown_docker, when: not is_in_docker | bool }
    - { role: autoware.ecu_system_setup.boot_shutdown_interface }
    - { role: autoware.ecu_system_setup.boot_shutdown_service }
    - { role: autoware.ecu_system_setup.cyclonedds }
    - { role: autoware.ecu_system_setup.docker_groups } # is required before docker build
    - { role: autoware.ecu_system_setup.iptables }
    - role: autoware.ecu_system_setup.media_streaming
      when: skip_media_streaming is not defined or not skip_media_streaming | bool
    - { role: autoware.ecu_system_setup.netplan }
    - { role: autoware.ecu_system_setup.ota_client }
    - { role: autoware.ecu_system_setup.rsyslog }
    - { role: autoware.ecu_system_setup.rqx_58g_firmware }
    - { role: autoware.ecu_system_setup.stop_auto_upgrade }
    - { role: autoware.ecu_system_setup.syslog_collector_client }
    - role: autoware.ecu_system_setup.tier4_camera_driver
      vars:
        dtb_sensor_type: isx021 # noqa var-naming[no-role-prefix]
      when: skip_tier4_camera_driver is not defined or not skip_tier4_camera_driver | bool
