- name: Execute x2-signage master playbook
  ansible.builtin.import_playbook: pilot_auto.dev_env.x2_signage

- name: Setup x2 x2-signage-cert
  hosts: localhost
  vars_files:
    - ./vars/x2_signage.yaml
    - ./vars/x2_signage_cert.yaml
  roles:
    - { role: autoware.ecu_system_setup.nftables }
