# cspell:ignore fintek
- name: Include vars
  hosts: localhost
  tasks:
    - name: Include common vars
      ansible.builtin.include_vars: ./vars/x2_common.yaml
    - name: Include vars for Sub ECU
      ansible.builtin.include_vars: ./vars/x2_sub.yaml

- name: Include additional playbook for common
  ansible.builtin.import_playbook: pilot_auto.dev_env.ecu_common

- name: Include playbook for development
  ansible.builtin.import_playbook: pilot_auto.dev_env.ecu_develop

- name: Setup ECU by additional roles
  hosts: localhost
  roles:
    # add your necessary roles
    - { role: autoware.ecu_system_setup.automatic_login }
    - { role: autoware.ecu_system_setup.boot_shutdown_service }
    - { role: autoware.ecu_system_setup.ip_routing_policy }
    - { role: autoware.ecu_system_setup.lenovo_keyboard }
    - { role: autoware.ecu_system_setup.rootfs_encrypt }
    - { role: autoware.ecu_system_setup.rsyslog }
    - { role: autoware.ecu_system_setup.syslog_collector_client }
    - { role: autoware.ecu_system_setup.fintek_can_driver }
    - { role: autoware.ecu_system_setup.marvell_switch_driver }
    - { role: autoware.ecu_system_setup.build_system_monitor }
    - role: autoware.ecu_system_setup.rviz
      when: skip_rviz is not defined or not skip_rviz | bool
    - { role: autoware.ecu_system_setup.screen_recorder }
    # - { role: x2_autoware } # Don't launch Autoware in Sub ECU until MRM design is finalized
    - { role: autoware.ecu_system_setup.domain_bridge }
    - { role: x2_can_adm }
    - { role: x2_configure_marvell_switch }
    - { role: x2_ptp4l }
    - { role: x2_disable_chrony } # Disable chrony service on Sub ECU to avoid conflicts with ptp4l
    - { role: x2_disable_greengrass_setup } # Disable the greengrass-v2-setup service on the Sub ECU to prevent an infinite setup loop.
    - { role: x2_dev_tools }
