# USBGuard rule for X2-Gen2 Main ECU
# Configured as https://drive.google.com/drive/folders/1L7DiaUBIhroqnAOmukMM4_6EFPTeDeHN
# cspell: ignore BATIGE Fintek

# xHCI Host Controller(Internally connected)
allow id 1d6b:0002 # for USB 2.0
allow id 1d6b:0003 # for USB 3.0

# 運転席裏
# Rules for USB 3.0 Devices
allow id 0bda:0411 via-port "2-1" # KU30-EN10K
allow id 0bda:0411 via-port "2-1.1" # KB-USB-R310
# Rules for USB 2.0 Devices
allow id 0bda:5411 via-port "1-2" # KU30-EN10K
allow id 0bda:5411 via-port "1-2.1" # KB-USB-R310
allow id 17ef:60ee via-port "1-2.1.1" # 4Y40X49522

# 後部ボックス前
# Rules for USB 3.0 Devices
allow id 0bda:0411 via-port "2-5" # KB-USB-R305
# Rules for USB 2.0 Devices
allow id 0bda:5411 via-port "1-6" # KB-USB-R305
allow id 17ef:60ee via-port "1-6.1" # 4Y40X49522

# 緊急車両検出用マイク
# Rules for USB 3.0 Devices
# No device
# Rules for USB 2.0 Devices
allow id 1a40:0101  via-port "1-5" # KB-USB-R212N
allow id 0d8c:2800 via-port "1-5.1" # MM-MCU06BKN

# 内部接続
allow id 2c42:1709 # Fintek USB to CAN BUS Bridge
