# Block any devices connected to unused USB ports
block id *:* via-port "1-1"
block id *:* via-port "1-3"
block id *:* via-port "1-4"
block id *:* via-port "2-1"


# Rules for internal USB devices
# xHCI Host Controller(Internally connected)
allow id 1d6b:0002 # for USB 2.0
allow id 1d6b:0003 # for USB 3.0

# CP2105 Dual USB to UART Bridge Controller
# (Internally connected, some of AVA-3510 does not have this device)
allow id 10c4:ea70

# MCP2210 USB to SPI Master(Internally connected)
allow id 04d8:00de



# Rules for external USB devices
# Buffalo USB Hub
allow id 0bda:5411 via-port "1-2" # via Lower USB 3.0 port for USB 2.0 Device
allow id 0bda:5411 via-port "1-2.1" # internal USB 2.0 hub
allow id 0bda:0411 via-port "2-2" # via Lower USB 3.0 port for USB 3.0 Device
allow id 0bda:0411 via-port "2-2.1" # internal USB 3.0 hub

# Lenovo TrackPoint Keyboard II
allow id 17ef:60ee via-port "1-2.1.2" # via USB 2.0 Hub

# USB microphone
allow id 0d8c:016c via-port "1-2.1.1" # via USB 2.0 Hub
