- name: Clone repository that contain install script
  block:
    - name: Set fact github_token
      ansible.builtin.set_fact:
        github_token: "{{ lookup('env', 'GITHUB_TOKEN') | default('') }}"
    # If github_token is not set, use ssh url. Otherwise, use https url with token.
    - name: Set fact repo_url and work_dir
      ansible.builtin.set_fact:
        repo_url: >-
          {{ 'https://' + github_token + '@github.com/tier4/jetson_iv_container.git' if github_token != '' else 'git@github.com:tier4/jetson_iv_container.git' }}
        work_dir: /tmp/jetson_iv_container
    - name: Clone jetson_iv_container
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ work_dir }}"
        depth: 1
        version: "{{ x2_addon_perception_jetson_iv_container_version }}"

- name: Execute install script
  block:
    - name: Set_fact script_name
      ansible.builtin.set_fact:
        script_name: addon_build.sh
    - name: Add executable permission to the script
      ansible.builtin.file:
        path: "{{ work_dir }}/native/{{ script_name }}"
        mode: 0755
    - name: Set base environment variables (PATH and HOME)
      ansible.builtin.set_fact:
        env_vars:
          PATH: /usr/local/cuda/bin:{{ ansible_env.PATH }}
          HOME: "{{ x2_addon_perception_jetson_container_install_dir }}"
          SSH_AUTH_SOCK: "{{ lookup('env', 'SSH_AUTH_SOCK') }}"
    # This Ansible playbook can be executed in the following environments:
    # 1. When executed on the Autoware evaluator, the GITHUB_TOKEN is set. Git cloning is performed using the HTTPS URL with the token.
    # 2. When executed on the target ECU with a valid SSH key, git cloning is performed using the SSH URL.
    # 3. When executed on the target ECU without a valid SSH key but via SSH agent forwarding, git cloning is performed using the SSH URL, enabled by the SSH_AUTH_SOCK environment variable.
    #
    # SSH_AUTH_SOCK is included in the environment variables to allow the script to use the SSH agent from the controlling host.
    # This is especially critical when the Ansible playbook is executed over an SSH connection, as it enables the script running on the remote machine to forward SSH credentials from the controlling host.
    # This allows private repositories to be cloned without requiring a GitHub token, by leveraging the SSH key configured on the controlling host.
    #
    # NOTE: For this setup to function correctly, the user must enable SSH agent forwarding by using the -A option when initiating the SSH connection to the remote host.
    # Example: ssh -A autoware@192.168.30.33

    - name: Add GITHUB_TOKEN to environment if token exists
      when: github_token is defined and github_token != ''
      ansible.builtin.set_fact:
        env_vars: "{{ env_vars | combine({'GITHUB_TOKEN': github_token}) }}"
    # - name: Print current env_vars
    #   ansible.builtin.debug:
    #     msg: "env_vars: {{ env_vars }}"
    - name: Execute the script
      ansible.builtin.command: "{{ work_dir }}/native/{{ script_name }}"
      become: true # become: true is required to handle sudo operation in the script
      environment: "{{ env_vars }}"
      register: execute_script_result
      changed_when: execute_script_result.rc != 0
    - name: Delete working directory
      ansible.builtin.file:
        path: "{{ work_dir }}"
        state: absent

- name: Install systemd service for automatic start
  block:
    - name: Create run script directory
      ansible.builtin.file:
        path: /opt/autoware/jetson-container-service
        state: directory
        mode: 0755
      become: true

    - name: Copy run script
      ansible.builtin.template:
        src: run.sh.j2
        dest: /opt/autoware/jetson-container-service/run.sh
        mode: 0755
      become: true

    - name: Copy service
      ansible.builtin.template:
        src: jetson-container.service.j2
        dest: /etc/systemd/system/jetson-container.service
        mode: 0755
      become: true

    - name: Enable service
      ansible.builtin.systemd:
        name: jetson-container.service
        daemon_reload: "{{ daemon_reload }}"
        enabled: true
        masked: false
      become: true
