# cSpell:ignore ruleset iifname oifname dport MQTTS
#!/usr/sbin/nft -f
# Packet Filter Settings for X2 Autoware Main ECU
# Setting are based on document below
# https://docs.google.com/spreadsheets/d/1B4NmnN7kwMShjgGxmq9rz1yjqxjKc94wl2ORxstDJZw

flush ruleset

define IF_HMI = vlan.500                                            # HMI Network Adapter
define IF_PERCEPTION = enp5s0f1                                     # Perception Network Adapter
define IF_MAIN_SUB_LIDAR = enp4s0                                   # Main/Sub/LiDAR Network Adapter
define IF_RADAR = vlan.19                                           # Radar Network Adapter

define IFs_ROUTER = { vlan.100, vlan.200, vlan.300, vlan.400 }      # Network Adapter Set to Internet Router
define IFs_INTERNAL = { $IF_HMI, $IF_PERCEPTION, $IF_MAIN_SUB_LIDAR, $IF_RADAR } # Network Adapter Set to Internal Network


table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;                 # input default policy drop
      iifname "lo" accept                                           # local loopback accept
      iifname $IFs_INTERNAL accept                                  # Internal network accept
      iifname $IFs_ROUTER ct state { established, related } accept  # LTE Router established/related accept
  }
  chain forward {
    type filter hook forward priority 0;
  }
  chain output {
    type filter hook output priority 0; policy drop;                # output default policy drop
      oifname "lo" accept                                           # local loopback accept
      oifname $IFs_INTERNAL accept                                  # Internal network accept
      oifname $IFs_ROUTER udp dport 53 accept                       # LTE Router DNS accept
      oifname $IFs_ROUTER udp dport 123 accept                      # NTP accept
      oifname $IFs_ROUTER tcp dport { 443, 8443 } accept            # HTTPS (OTA, FMS REST API) accept
      oifname $IFs_ROUTER udp dport 8883 accept                     # MQTTS (FMS data sharing / UDP) accept
      oifname $IFs_ROUTER tcp dport 8883 accept                     # MQTTS (FMS data sharing / TCP) accept
  }
}
