- name: Create cyclonedds directory
  ansible.builtin.file:
    path: /opt/autoware/cyclonedds/
    state: directory
    mode: 0755
  become: true

- name: Copy config(galactic)
  ansible.builtin.template:
    src: cyclonedds_galactic.xml.jinja2
    dest: /opt/autoware/cyclonedds/cyclonedds_for_redundancy.xml
    mode: 0755
  become: true
  when: ros_distro == "galactic" or ros_distro == "foxy"

- name: Copy config
  ansible.builtin.template:
    src: cyclonedds.xml.jinja2
    dest: /opt/autoware/cyclonedds/cyclonedds_for_redundancy.xml
    mode: 0755
  become: true
  when: ros_distro == "humble"
