- name: Disable chrony service
  ansible.builtin.systemd:
    name: chrony.service
    daemon_reload: "{{ daemon_reload }}"
    enabled: false
    masked: true
    state: stopped
  failed_when: false
  become: true
