name: build-and-test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to checkout
        required: true
        default: update-resolved-repos-main
      create-pr:
        description: Create PR after build and test
        required: false
        default: false
        type: boolean
  schedule:
    # Run at midnight in Japan
    - cron: 0 15 * * *

jobs:
  build-and-test:
    runs-on: ubuntu-22.04-m
    container: ${{ matrix.container }}${{ matrix.container-suffix }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - humble
        container-suffix:
          - -cuda
        include:
          - rosdistro: humble
            container: ghcr.io/autowarefoundation/autoware:universe-devel
            build-depends-repos: ""
    env:
      CCACHE_DIR: /root/.ccache
      CCACHE_SIZE: 1G
      CC: /usr/lib/ccache/gcc
      CXX: /usr/lib/ccache/g++
      CREATE_PR: ${{ github.event_name == 'schedule' || github.event.inputs.create-pr == 'true' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'schedule' && 'update-resolved-repos-main' || github.event.inputs.branch }}

      - name: Install vcstool and ccache
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip ccache gh
          pip install --no-cache-dir vcstool

      - name: Create ccache directory
        run: |
          mkdir -p ${CCACHE_DIR}
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Limit ccache size
        run: |
          rm -f "${CCACHE_DIR}/ccache.conf"
          echo -e "max_size = ${CCACHE_SIZE}" > "${CCACHE_DIR}/ccache.conf"
        shell: bash

      - name: Attempt to restore ccache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: |
            ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-

      - name: Show ccache stats before build and reset stats
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
          ccache --zero-stats
        shell: bash

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < .autoware_resolved.repos --shallow

      - name: Show disk space before the tasks
        run: df -h

      - name: Remove exec_depend
        uses: autowarefoundation/autoware-github-actions/remove-exec-depend@v1

      - name: Get self packages
        id: get-self-packages
        uses: autowarefoundation/autoware-github-actions/get-self-packages@v1

      - name: Build
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}

      - name: Show ccache stats after build
        run: |
          du -sh ${CCACHE_DIR} && ccache -s
        shell: bash

      - name: Upload ccache to cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.arch }}-${{ matrix.rosdistro }}-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Test
        if: ${{ steps.get-self-packages.outputs.self-packages != '' }}
        id: test
        uses: autowarefoundation/autoware-github-actions/colcon-test@v1
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: ${{ steps.get-self-packages.outputs.self-packages }}
          build-depends-repos: ${{ matrix.build-depends-repos }}
          packages-skip: |
            boost_serial_driver
            boost_tcp_driver
            boost_udp_driver
            eagleye_can_velocity_converter
            eagleye_coordinate
            eagleye_fix2kml
            eagleye_geo_pose_converter
            eagleye_geo_pose_fusion
            eagleye_gnss_converter
            eagleye_msgs
            eagleye_navigation
            eagleye_rt
            eagleye_tf
            jpn_signal_mqtt_interface
            llh_converter
            negotiated_interfaces
            pe_ars408_ros
            rclcpp
            rtklib_bridge
            tamagawa_imu_driver
            autoware_common_msgs
            autoware_control_msgs
            autoware_internal_msgs
            autoware_localization_msgs
            autoware_map_msgs
            autoware_perception_msgs
            autoware_planning_msgs
            autoware_sensing_msgs
            autoware_system_msgs
            autoware_vehicle_msgs
            autoware_internal_debug_msgs
            autoware_internal_perception_msgs

      - name: Save coverage as artifacts
        if: ${{ steps.test.outputs.coverage-report-files != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            lcov/total_coverage.info
            coveragepy/.coverage
          if-no-files-found: warn

      - name: Show disk space after the tasks
        run: df -h

      - name: Mark repo as safe
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Create Pull Request
        if: ${{ env.CREATE_PR == 'true' }}
        run: |
          gh pr create \
            --base ${{ github.event.repository.default_branch }} \
            --head update-resolved-repos-main \
            --title "chore: update default branch commits in .autoware_resolved.repos" \
            --body "This PR updates the .autoware_resolved.repos file with the latest commit hashes from the default branch. This PR is automatically created by the nightly workflow and has been verified with build and test." \
            --label "tag:run-build-test" \
            --reviewer dkoldaev
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Enable auto-merge for PR
        if: ${{ env.CREATE_PR == 'true' }}
        run: |
          PR_NUMBER=$(gh pr list --head update-resolved-repos-main --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge --auto --squash "$PR_NUMBER" --delete-branch
          fi
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
