name: Check Base Tags

on:
  pull_request:
  # Remove path filtering to make it run on all PRs
  # paths:
  #   - autoware.repos

jobs:
  check-base-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need history to compare changes

      - name: Check if autoware.repos was modified
        id: check_modified
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -q "autoware.repos"; then
            echo "file_changed=true" >> $GITHUB_OUTPUT
          else
            echo "file_changed=false" >> $GITHUB_OUTPUT
            echo "autoware.repos was not modified in this PR, skipping checks."
          fi

      - name: Install yq
        if: steps.check_modified.outputs.file_changed == 'true'
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Make script executable
        if: steps.check_modified.outputs.file_changed == 'true'
        run: chmod +x .github/scripts/check-base-tag.sh

      - name: Check base tags
        if: steps.check_modified.outputs.file_changed == 'true'
        run: .github/scripts/check-base-tag.sh
