name: create-pilot-auto-image

on:
  workflow_dispatch:
    inputs:
      release-branch-or-tag-name:
        description: The name of the beta branch or tag to release
        type: string
        required: true
      update-latest:
        description: Update the latest tag
        type: boolean
        required: true
        default: true

env:
  ROS_DISTRO: humble
  BASE_IMAGE: ghcr.io/tier4/pilot-auto/base-image

jobs:
  create-pilot-auto-image:
    # runs-on: ubuntu-latest # Error: "No space left on device"
    runs-on: ubuntu-22.04-m
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set env
        run: |
          echo "WORKSPACE_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "CREATE_DATE=$(date +'%Y%m%d_%H%M(%Z)')" >> $GITHUB_ENV

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set tag name
        id: set-tag-name
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            REF_NAME="${{ github.event.inputs.release-branch-or-tag-name }}"
          else
            REF_NAME="${{ github.ref_name }}"
          fi

          echo "ref-name=$REF_NAME" >> $GITHUB_OUTPUT
          if [[ "$REF_NAME" =~ ^alpha ]]; then
            echo "tag-name=${REF_NAME#**/}-alpha" >> $GITHUB_OUTPUT
          else
            echo "tag-name=${REF_NAME#**/}" >> $GITHUB_OUTPUT
          fi

      - name: Check ROS 2 Package Versions
        run: |
          sudo apt update && sudo apt install curl
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
          curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb"
          sudo apt install /tmp/ros2-apt-source.deb
          sudo apt update
          echo "ROS_DESKTOP_VER=$(apt-cache madison ros-${ROS_DISTRO}-desktop | grep -v Sources | cut -d \| -f 2 | cut -c 2-)" >> $GITHUB_ENV

      - name: Install vcstool
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip
          pip install --no-cache-dir vcstool

      - name: set description
        id: set-description
        run: |
          echo "img-description=${{ env.CREATE_DATE }}, ros-${{ env.ROS_DISTRO }}-desktop:${{ env.ROS_DESKTOP_VER }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ github.ref_name }}

      - name: Create build context
        run: |
          mkdir -p build-context/docker/pilot-auto
          cp -r docker/pilot-auto/* build-context/docker/pilot-auto/

      - name: Checkout repository to reference version
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ steps.set-tag-name.outputs.ref-name }}
          clean: false

      - name: Set target name for beta branches
        id: set-target-name
        run: |
          if [[ "${{ steps.set-tag-name.outputs.ref-name }}" =~ "beta/" ]]; then
            echo "target-name=${{ steps.set-tag-name.outputs.ref-name }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          logout: false
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git config for private repositories
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/.insteadOf 'https://github.com/'
          git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/.insteadOf 'git@github.com:'

      - name: Create token file
        run: |
          touch github_token
          echo "${{ steps.generate-token.outputs.token }}" >> github_token
        shell: bash

      - name: Fetch source files
        run: |
          mkdir -p build-context/src
          vcs import --shallow build-context/src < autoware.repos

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ env.WORKSPACE_ROOT }}/build-context/docker/pilot-auto/Dockerfile
          context: ${{ env.WORKSPACE_ROOT }}/build-context
          secrets: id=github_token,src=github_token
          tags: |
            ${{ github.event.inputs.update-latest == 'true' && format('ghcr.io/{0}/pilot-auto:latest', github.repository) || '' }}
            ghcr.io/${{ github.repository }}:${{ steps.set-tag-name.outputs.tag-name }}
          build-args: |
            DESCRIPTION=${{ steps.set-description.outputs.img-description }}
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            BASE_IMAGE=${{ env.BASE_IMAGE }}:${{ steps.set-tag-name.outputs.tag-name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ steps.set-tag-name.outputs.tag-name }}
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}-buildcache:${{ steps.set-tag-name.outputs.tag-name }},mode=max
          outputs: type=registry
          provenance: false
          sbom: false
