name: create-base-image

on:
  workflow_dispatch:
    inputs:
      release-branch-or-tag-name:
        description: The name of the beta branch or tag to release
        type: string
        required: true
      tag-suffix:
        description: Optional suffix for the tag name (e.g. "pilot-auto/base-image:v0.47-dev" will be pushed with "dev" as the suffix)
        type: string
        required: false
        default: ""
      update-latest:
        description: Update the latest tag
        type: boolean
        required: true
        default: true
      include-cuda-drivers:
        description: Include CUDA drivers
        type: boolean
        required: true
        default: false
      include-nvidia:
        description: Include NVIDIA packages
        type: boolean
        required: true
        default: false

env:
  ROS_DISTRO: humble
  BASE_IMAGE: ubuntu:22.04

jobs:
  create-base-image:
    # runs-on: ubuntu-latest # Error: "No space left on device"
    runs-on: ubuntu-22.04-m
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set env
        run: |
          echo "WORKSPACE_ROOT=$(pwd)" >> $GITHUB_ENV
          echo "CREATE_DATE=$(date +'%Y%m%d_%H%M(%Z)')" >> $GITHUB_ENV

          # Set SETUP_ARGS based on workflow_dispatch inputs
          SETUP_ARGS="local_dev_env"
          if [ "${{ github.event.inputs.include-cuda-drivers }}" = "false" ]; then
            SETUP_ARGS="$SETUP_ARGS --no-cuda-drivers"
          fi
          if [ "${{ github.event.inputs.include-nvidia }}" = "false" ]; then
            SETUP_ARGS="$SETUP_ARGS --no-nvidia"
          fi
          echo "SETUP_ARGS=$SETUP_ARGS" >> $GITHUB_ENV

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set tag name
        id: set-tag-name
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            REF_NAME="${{ github.event.inputs.release-branch-or-tag-name }}"
          else
            REF_NAME="${{ github.ref_name }}"
          fi

          echo "ref-name=$REF_NAME" >> $GITHUB_OUTPUT
          if [[ "$REF_NAME" =~ ^alpha ]]; then
            echo "tag-name=${REF_NAME#**/}-alpha" >> $GITHUB_OUTPUT
          else
            echo "tag-name=${REF_NAME#**/}" >> $GITHUB_OUTPUT
          fi

      - name: Check ROS 2 Package Versions
        run: |
          sudo apt update && sudo apt install curl
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
          curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb"
          sudo apt install /tmp/ros2-apt-source.deb
          sudo apt update
          echo "ROS_DESKTOP_VER=$(apt-cache madison ros-${ROS_DISTRO}-desktop | grep -v Sources | cut -d \| -f 2 | cut -c 2-)" >> $GITHUB_ENV

      - name: set description
        id: set-description
        run: |
          DESCRIPTION="${{ env.CREATE_DATE }}, ros-${{ env.ROS_DISTRO }}-desktop:${{ env.ROS_DESKTOP_VER }}"
          if [ "${{ github.event.inputs.include-cuda-drivers }}" = "true" ]; then
            DESCRIPTION="$DESCRIPTION, with-cuda-drivers"
          fi
          if [ "${{ github.event.inputs.include-nvidia }}" = "true" ]; then
            DESCRIPTION="$DESCRIPTION, with-nvidia"
          fi
          echo "img-description=$DESCRIPTION" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ steps.set-tag-name.outputs.ref-name }}

      - name: Set target name for beta branches
        id: set-target-name
        run: |
          if [[ "${{ steps.set-tag-name.outputs.ref-name }}" =~ "beta/" ]]; then
            echo "target-name=${{ steps.set-tag-name.outputs.ref-name }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          logout: false
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git config for private repositories
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/.insteadOf 'https://github.com/'
          git config --global url.https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/.insteadOf 'git@github.com:'

      - name: Create token file
        run: |
          touch github_token
          echo "${{ steps.generate-token.outputs.token }}" >> github_token
        shell: bash

      - name: Create build context
        run: |
          mkdir -p build-context/docker/base-image
          cp -r docker/base-image/* build-context/docker/base-image/
          cp autoware.repos simulator.repos tools.repos setup-dev-env.sh ansible-galaxy-requirements.yaml amd64.env arm64.env build-context/
          cp -r ansible build-context/

      - name: Set image tag suffix
        id: set-tag-suffix
        run: |
          TAG_SUFFIX=""
          if [ "${{ github.event.inputs.tag-suffix }}" != "" ]; then
            TAG_SUFFIX="${TAG_SUFFIX}-${{ github.event.inputs.tag-suffix }}"
          fi
          if [ "${{ github.event.inputs.include-cuda-drivers }}" = "true" ]; then
            TAG_SUFFIX="${TAG_SUFFIX}-cuda"
          fi
          if [ "${{ github.event.inputs.include-nvidia }}" = "true" ]; then
            TAG_SUFFIX="${TAG_SUFFIX}-nvidia"
          fi
          echo "tag-suffix=$TAG_SUFFIX" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: docker/base-image/Dockerfile.bi
          set: |
            *.context=${{ env.WORKSPACE_ROOT }}/build-context
            *.secrets=id=github_token,src=github_token
          tags: |
            ${{ github.event.inputs.update-latest == 'true' && format('ghcr.io/{0}/base-image:latest{1}', github.repository, steps.set-tag-suffix.outputs.tag-suffix) || '' }}
            ghcr.io/${{ github.repository }}/base-image:${{ steps.set-tag-name.outputs.tag-name }}${{ steps.set-tag-suffix.outputs.tag-suffix }}
          build-args: |
            DESCRIPTION=${{ steps.set-description.outputs.img-description }}
            GITHUB_TOKEN=${{ steps.generate-token.outputs.token }}
            BASE_IMAGE=${{ env.BASE_IMAGE }}
            ROS_DISTRO=${{ env.ROS_DISTRO }}
            SETUP_ARGS=${{ env.SETUP_ARGS }}
