name: setup-local-dev-env

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-local-dev-env:
    runs-on: ubuntu-22.04-m
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Show disk space
        if: always()
        run: |
          df -h

      - name: Create pipx symlink
        run: |
          if [ -f /opt/pipx/bin/pipx ]; then
            sudo ln -sf /opt/pipx/bin/pipx /usr/bin/pipx
          else
            which pipx | xargs -I{} sudo ln -sf {} /usr/bin/pipx
          fi

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y -v local_dev_env
