name: setup-ecu

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  make-sure-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:run-build-test

  setup-ecu:
    needs: make-sure-label-is-present
    if: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        playbook:
          - ecu_setup
        include:
          - playbook: ecu_setup
            additional_args: -y -v -e vehicle_id=1234
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run setup script
        run: |
          ./setup-ecu.sh ${{ matrix.playbook }} ${{ matrix.additional_args }} -e reload_systemd=no
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
