# Batch update base repos for all released versions
name: Update Repos Base from Vanilla (Batch)

on:
  schedule:
    - cron: 30 22 * * * # Daily at 07:30 JST
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      release-version-pairs: ${{ steps.set-matrix.outputs.release-version-pairs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.49.2/yq_linux_amd64
          echo "be2c0ddcf426b6a231648610ec5d1666ae50e9f6473e82f6486f9f4cb6e3e2f7  /usr/local/bin/yq" | sha256sum -c -
          sudo chmod a+x /usr/local/bin/yq

      - name: Generate release version/vanilla version matrix
        id: set-matrix
        run: |
          # Add all releases
          RELEASE_VERSION_PAIRS=$(yq '.releases[] | {"version": .version, "vanilla_version": .parent.version}' -o=json .release_info.yaml | jq -s '.')

          echo "release-version-pairs=${RELEASE_VERSION_PAIRS}" >> $GITHUB_OUTPUT
          echo "Generated matrix: ${RELEASE_VERSION_PAIRS}"

  update-base-main:
    uses: ./.github/workflows/update-repos-base.yaml
    with:
      branch: main
      vanilla_branch: stable
    secrets: inherit

  update-base-releases:
    needs: generate-matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.release-version-pairs) }}
      fail-fast: false
      max-parallel: 5
    uses: ./.github/workflows/update-repos-base.yaml
    with:
      branch: beta/${{ matrix.version }}
      vanilla_branch: beta/${{ matrix.vanilla_version }}
    secrets: inherit
