name: vcs-import

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  workflow_dispatch:

jobs:
  make-sure-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:run-build-test

  load-env:
    needs: make-sure-label-is-present
    if: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }}
    uses: ./.github/workflows/load-env.yaml

  vcs-import:
    needs: load-env
    runs-on: ubuntu-22.04
    container: ros:${{ needs.load-env.outputs.rosdistro }}
    steps:
      # workaround until the fix release in the official ros image
      - name: Delete old ros2 apt source
        run: |
          rm -f /etc/apt/sources.list.d/ros2-latest.list
          rm -f /usr/share/keyrings/ros2-latest-archive-keyring.gpg

      - name: Setup new ros2 apt source
        run: |
          sudo apt-get update && sudo apt-get install curl
          export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}')
          curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb"
          sudo apt install /tmp/ros2-apt-source.deb

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install pip for rosdep
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip

      - name: Register AutonomouStuff repository
        uses: autowarefoundation/autoware-github-actions/register-autonomoustuff-repository@v1
        with:
          rosdistro: ${{ needs.load-env.outputs.rosdistro }}

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Run vcs import
        run: |
          mkdir src
          vcs import src < autoware.repos --shallow
          vcs import src < simulator.repos --shallow
          vcs import src < tools.repos --shallow

      - name: Run vcs export
        run: |
          vcs export --exact src || true

      - name: Run rosdep install
        run: |
          sudo apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths src --ignore-src --rosdistro ${{ needs.load-env.outputs.rosdistro }}
