name: parameter-check

on:
  pull_request:
    types:
      - labeled
    paths:
      - autoware.repos

# cspell: ignore deepdiff
jobs:
  make-sure-label-is-present:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/make-sure-label-is-present.yaml@v1
    with:
      label: tag:run-parameter-check

  load-env:
    needs: make-sure-label-is-present
    if: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }} && contains(github.event.pull_request.changed_files, 'autoware.repos')
    uses: ./.github/workflows/load-env.yaml

  yaml-test:
    needs: load-env
    if: ${{ needs.make-sure-label-is-present.outputs.result == 'true' }} && contains(github.event.pull_request.changed_files, 'autoware.repos')
    runs-on: ubuntu-22.04
    container: ros:${{ needs.load-env.outputs.rosdistro }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Set git config
        uses: autowarefoundation/autoware-github-actions/set-git-config@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Install yaml diff dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip
          pip3 install pyyaml pandas tabulate deepdiff

      # Temp: until sxpf and c2-readout-delay-setter is visible in CI environment
      - name: Set up yq
        uses: chrisdickinson/setup-yq@v1.0.1
        with:
          yq-version: v4.49.2

      - name: Run vcs import
        run: |
          mkdir src
          # import all repos (no filtering)
          ./repos-filter.sh autoware.repos main | vcs import src --shallow # temp: until sxpf and c2-readout-delay-setter is visible in CI environment
          # vcs import src --shallow < autoware.repos

      - name: Run yaml diff test
        run: |
          python3 .github/workflows/scripts/yaml_diff.py
          cat yaml_diff_report.md

      - name: Run Publish Result to the Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('yaml_diff_report.md', 'utf8');  // Read the report file content
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: result
            })
