fstab_entries: # noqa var-naming[no-role-prefix]
  - mount_specifier: LABEL=ROSBAG_INTERNAL
    mount_point: /mnt/ROSBAG
    fs_type: ext4
    options: nofail
  - mount_specifier: LABEL=TMP
    mount_point: /mnt/TMP
    fs_type: ext4
    options: nofail
  - mount_specifier: /mnt/TMP/tmp
    mount_point: /mnt/LOG
    fs_type: none
    options: bind,nofail
