# cspell: ignore btrfs luks

# dssad_packer
dssad_packer_param_template: dssad_packer/dssad_packer_params_x2.yaml.jinja2
dssad_encryption_type: opal
# - opal
opal_disk:
  device: /dev/sda
  partition_label: DSSAD
  filesystem: btrfs
  mountpoint: /mnt/DSSAD
